import { createSSRApp, h } from "vue";
import { renderToString } from "vue/server-renderer";
import { createInertiaApp } from "@inertiajs/vue3";
import createServer from "@inertiajs/vue3/server";
import PrimeVue from "primevue/config";
import Aura from "@primeuix/themes/aura";
import { createI18n } from "vue-i18n";
//#region node_modules/laravel-vite-plugin/inertia-helpers/index.js
async function resolvePageComponent(path, pages) {
	for (const p of Array.isArray(path) ? path : [path]) {
		const page = pages[p];
		if (typeof page === "undefined") continue;
		return typeof page === "function" ? page() : page;
	}
	throw new Error(`Page not found: ${path}`);
}
var ar_default = {
	auth: {
		"login": "تسجيل الدخول",
		"signIn": "تسجيل الدخول",
		"useAdminAccount": "استخدم حساب المشرف للوصول إلى لوحة التحكم.",
		"email": "البريد الإلكتروني",
		"password": "كلمة المرور",
		"rememberMe": "تذكرني",
		"appLogoAlt": "شعار {appName}"
	},
	nav: {
		"dashboard": "لوحة التحكم",
		"whatsapp": "واتساب",
		"users": "المستخدمون",
		"roles": "الأدوار",
		"plans": "الخطط",
		"monthlyPlans": "الخطط الشهرية",
		"centers": "المراكز",
		"groups": "المجموعات",
		"students": "الطلاب",
		"certificates": "الشهادات",
		"certificateDesign": "تصميم الشهادات",
		"evaluations": "التقييمات",
		"homeworks": "الواجبات",
		"absenceRules": "قواعد الغياب",
		"messageTemplates": "قوالب الرسائل",
		"activityLogs": "سجل النشاط",
		"settings": "الإعدادات",
		"management": "الإدارة",
		"lists": "القوائم",
		"studentTools": "ادوات الطلاب"
	},
	topbar: {
		"openSidebar": "فتح الشريط الجانبي",
		"expandSidebar": "توسيع الشريط الجانبي",
		"collapseSidebar": "طي الشريط الجانبي",
		"lightMode": "الوضع الفاتح",
		"darkMode": "الوضع الداكن",
		"enterFullscreen": "الدخول إلى ملء الشاشة",
		"exitFullscreen": "الخروج من ملء الشاشة",
		"logout": "تسجيل الخروج",
		"admin": "المشرف",
		"openProfileMenu": "فتح قائمة الملف الشخصي"
	},
	common: {
		"app": "تطبيق",
		"search": "بحث",
		"create": "إنشاء",
		"cancel": "إلغاء",
		"edit": "تعديل",
		"delete": "حذف",
		"history": "السجل",
		"save": "حفظ",
		"saveChanges": "حفظ التغييرات",
		"close": "إغلاق",
		"loading": "جاري التحميل...",
		"id": "المعرف",
		"actions": "الإجراءات",
		"noRecords": "لا توجد بيانات.",
		"records": "السجلات",
		"selectedCount": "{0} محدد",
		"na": "غير متوفر",
		"yes": "نعم",
		"no": "لا",
		"active": "فعال",
		"inactive": "غير فعال",
		"success": "نجاح",
		"error": "خطأ",
		"info": "معلومة",
		"required": "مطلوب"
	},
	breadcrumbs: {
		"ariaLabel": "مسار التنقل",
		"admin": "الإدارة",
		"dashboard": "لوحة التحكم",
		"whatsapp": "واتساب",
		"users": "المستخدمون",
		"roles": "الأدوار",
		"plans": "الخطط",
		"monthlyPlans": "الخطط الشهرية",
		"centers": "المراكز",
		"groups": "المجموعات",
		"students": "الطلاب",
		"certificates": "الشهادات",
		"certificateDesign": "تصميم الشهادات",
		"evaluations": "التقييمات",
		"homeworks": "الواجبات",
		"absenceRules": "قواعد الغياب",
		"messageTemplates": "قوالب الرسائل",
		"activityLogs": "سجل النشاط",
		"settings": "الإعدادات",
		"password": "كلمة المرور",
		"create": "إنشاء",
		"edit": "تعديل"
	},
	profile: {
		"updatePassword": "تحديث كلمة المرور",
		"passwordDescription": "غيّر كلمة مرور حسابك بشكل آمن.",
		"currentPassword": "كلمة المرور الحالية",
		"newPassword": "كلمة المرور الجديدة"
	},
	users: {
		"title": "المستخدمون",
		"tableTitle": "جدول المستخدمين",
		"searchUsers": "بحث المستخدمين",
		"createUser": "إنشاء مستخدم",
		"editUser": "تعديل مستخدم",
		"newUser": "مستخدم جديد",
		"addNew": "أضف حساب مستخدم جديد إلى النظام.",
		"editDescription": "حدّث بيانات المستخدم أو عيّن كلمة مرور جديدة.",
		"newUserDescription": "املأ جميع الحقول المطلوبة لإنشاء مستخدم.",
		"name": "الاسم",
		"role": "الدور",
		"confirmPassword": "تأكيد كلمة المرور",
		"newPassword": "كلمة المرور الجديدة",
		"createdAt": "تاريخ الإنشاء",
		"deleteConfirm": "حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteUser": "حذف المستخدم"
	},
	roles: {
		"title": "الأدوار",
		"tableTitle": "جدول الأدوار",
		"searchRoles": "بحث الأدوار",
		"createRole": "إنشاء دور",
		"editRole": "تعديل دور",
		"permissions": "الصلاحيات",
		"roleName": "اسم الدور",
		"createdAt": "تاريخ الإنشاء",
		"permissionsCount": "الصلاحيات",
		"createDescription": "عرّف دورًا واربطه بالصلاحيات للتحكم في الوصول.",
		"editDescription": "حدّث اسم الدور وربط الصلاحيات.",
		"saveRole": "حفظ الدور",
		"deleteConfirm": "حذف الدور \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteRole": "حذف الدور",
		"adminRoleProtected": "دور المشرف محمي ولا يمكن تعديله أو حذفه."
	},
	plans: {
		"title": "الخطط",
		"tableTitle": "جدول الخطط",
		"searchPlans": "بحث الخطط",
		"createPlan": "إنشاء خطة",
		"editPlan": "تعديل خطة",
		"newPlan": "خطة جديدة",
		"planName": "اسم الخطة",
		"pointsCount": "عدد النقاط",
		"pointsActions": "نقاط الخطة",
		"exportPoints": "استخراج نقاط الخطة",
		"importPoints": "إدخال نقاط الخطة",
		"importFile": "ملف XLSX",
		"importFileRequired": "يرجى اختيار ملف XLSX.",
		"importHint": "استيراد الملف يستبدل نقاط هذه الخطة بالأعمدة الأساسية. ملف التصدير يعرض sort_order والوزن وهل العنصر منفرد.",
		"importFailed": "تعذر إدخال نقاط الخطة.",
		"importSuccess": "تم إدخال نقاط الخطة بنجاح.",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أضف نوع خطة جديد للطلاب.",
		"editDescription": "حدّث تفاصيل الخطة المحددة.",
		"deleteConfirm": "حذف الخطة \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deletePlan": "حذف الخطة"
	},
	monthlyPlans: {
		"title": "الخطط الشهرية",
		"center": "المركز",
		"group": "المجموعة",
		"groupOptional": "المجموعة (اختياري)",
		"createPlan": "إنشاء خطة",
		"newPlan": "خطة جديدة",
		"createDescription": "اختر المركز والشهر والسنة وفترة البداية والنهاية لإنشاء خطة شهرية محفوظة. اختيار المجموعة اختياري؛ بدون مجموعة سيتم إنشاء خطة لكل مجموعة في المركز.",
		"searchSavedPlans": "بحث الخطط المحفوظة",
		"savedPlanDetails": "تفاصيل الخطة المحفوظة",
		"backToSavedPlans": "العودة للخطط المحفوظة",
		"planItems": "عناصر الخطة",
		"generate": "حفظ الخطة",
		"generateHint": "سيتم توليد الخطة الشهرية وحفظها لطلاب مركز {center} ضمن الفترة المحددة.",
		"generated": "تم توليد الخطة الشهرية.",
		"alreadyExists": "هذه الخطة محفوظة مسبقًا وسيتم عرضها.",
		"generateFailed": "تعذر توليد الخطة الشهرية.",
		"loadFailed": "تعذر تحميل الخطط الشهرية.",
		"centerRequired": "اختر مركزًا قبل التوليد.",
		"groupRequired": "اختر مجموعة قبل توليد الخطة الشهرية.",
		"noPlans": "لا توجد خطط شهرية لهذه المحددات.",
		"savedPlans": "الخطط المحفوظة",
		"savedPlansHint": "كل مجموعة يمكن أن تملك خطة واحدة فقط لنفس الشهر والسنة.",
		"noSavedPlans": "لا توجد خطط محفوظة لهذه المحددات.",
		"viewPlan": "عرض",
		"openPublicReport": "فتح رابط الخطة",
		"deletePlan": "حذف الخطة",
		"deleteConfirm": "حذف خطة {group} لشهر {month} {year}؟",
		"deleted": "تم حذف الخطة الشهرية بنجاح.",
		"deleteFailed": "تعذر حذف الخطة الشهرية.",
		"refreshFuture": "إعادة التوزيع",
		"refreshFutureTitle": "تعديل الخطة من تاريخ محدد",
		"refreshFromDate": "من تاريخ",
		"refreshFutureHint": "سيتم ترك الأيام السابقة كما هي، وحفظ أيام العطل المحددة، ثم إعادة توزيع هذا التاريخ وما بعده.",
		"refreshFutureConfirm": "إعادة توزيع الخطة من تاريخ {date} وما بعده؟",
		"generatedAt": "تاريخ الإنشاء",
		"month": "الشهر",
		"year": "السنة",
		"startDate": "تاريخ البداية",
		"endDate": "تاريخ النهاية",
		"holidayDates": "أيام العطل",
		"noHolidayDates": "لا توجد أيام عطل محددة",
		"removeHolidayDate": "حذف يوم العطلة",
		"clearHolidayDates": "مسح أيام العطل",
		"period": "الفترة",
		"monthlyGridHint": "أسماء الطلاب على اليمين، والواجبات موزعة على أيام دوام المركز خلال الفترة المحددة.",
		"student": "الطالب",
		"searchStudent": "بحث باسم الطالب",
		"searchStudentPlaceholder": "ابحث باسم الطالب...",
		"noStudentSearchResults": "لا يوجد طلاب بهذا الاسم.",
		"studentsCount": "عدد الطلاب",
		"workingDaysCount": "أيام الدوام",
		"date": "التاريخ",
		"items": "العناصر",
		"itemsCount": "عدد العناصر",
		"skippedItems": "العناصر المتخطاة",
		"weight": "الوزن",
		"totalWeight": "مجموع الوزن",
		"maxDailyWeight": "الحد اليومي",
		"dailyWeightLimit": "حد اليوم",
		"dailyWeightLimits": "حدود الأيام",
		"standalone": "منفرد",
		"completionPercentage": "نسبة الإنجاز",
		"completedItems": "المنجز",
		"dayCompletion": "إنجاز اليوم",
		"completedOnTime": "منجز بالموعد",
		"notCompletedOnTime": "غير منجز بالموعد",
		"completedOnPlanDate": "منجز بيوم الخطة",
		"completedOnDate": "منجز بتاريخ {date}",
		"completedBeforeDueDate": "منجز مسبقًا {date}",
		"notCompleted": "غير منجز",
		"evaluationAbsence": "غياب من التقييم",
		"months": {
			"1": "كانون الثاني",
			"2": "شباط",
			"3": "آذار",
			"4": "نيسان",
			"5": "أيار",
			"6": "حزيران",
			"7": "تموز",
			"8": "آب",
			"9": "أيلول",
			"10": "تشرين الأول",
			"11": "تشرين الثاني",
			"12": "كانون الأول"
		}
	},
	centers: {
		"title": "المراكز",
		"tableTitle": "جدول المراكز",
		"searchCenters": "بحث المراكز",
		"createCenter": "إنشاء مركز",
		"editCenter": "تعديل مركز",
		"newCenter": "مركز جديد",
		"centerName": "اسم المركز",
		"studentType": "نوع الطلاب",
		"studentTypeHint": "حدّد نوع الطلاب المسجلين في هذا المركز.",
		"maleStudents": "ذكور",
		"femaleStudents": "إناث",
		"certificateSettings": "إعدادات الشهادة",
		"certificateSettingsDescription": "خصّص هوية المركز وظهور توقيع المدير على شهادات طلابه.",
		"certificateName": "اسم المركز على الشهادة",
		"certificateNameHint": "اتركه فارغًا لاستخدام اسم المركز الأساسي.",
		"showCenterManagerSignature": "إظهار توقيع مدير المركز",
		"centerManagerSignatureHint": "عند الإخفاء يُزال شعار المركز وعنوان المدير وختمه وتوقيعه، وتنتقل هوية المشروع إلى موضع المركز.",
		"phone": "الهاتف",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneRequired": "رقم الهاتف مطلوب.",
		"phoneErrorInvalid": "رقم غير صالح.",
		"phoneErrorInvalidCountryCode": "مفتاح الدولة غير صالح.",
		"phoneErrorTooShort": "الرقم قصير جدًا.",
		"phoneErrorTooLong": "الرقم طويل جدًا.",
		"phoneErrorInvalidLength": "طول الرقم غير صالح.",
		"whatsappGroup": "معرّف مجموعة واتساب",
		"noWhatsappGroups": "لم يتم العثور على مجموعات واتساب. اربط واتساب أولاً ثم أعد تحميل الصفحة.",
		"workingDays": "أيام الدوام",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أضف مركزًا وحدد نوع طلابه ورقم الهاتف.",
		"editDescription": "حدّث بيانات المركز ونوع طلابه؛ إعدادات الدوام وواتساب تُدار من المجموعات.",
		"deleteConfirm": "حذف المركز \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteCenter": "حذف المركز"
	},
	groups: {
		"title": "المجموعات",
		"tableTitle": "جدول المجموعات",
		"searchGroups": "بحث المجموعات",
		"createGroup": "إنشاء مجموعة",
		"editGroup": "تعديل مجموعة",
		"newGroup": "مجموعة جديدة",
		"groupName": "اسم المجموعة",
		"center": "المركز",
		"whatsappGroup": "معرّف مجموعة واتساب",
		"noWhatsappGroups": "لم يتم العثور على مجموعات واتساب. اربط واتساب أولاً ثم أعد تحميل الصفحة.",
		"workingDays": "أيام دوام المجموعة",
		"createdAt": "تاريخ الإنشاء",
		"openHomeworkReport": "فتح صفحة واجبات المجموعة",
		"openPointsRanking": "فتح ترتيب الطلاب حسب النقاط",
		"createDescription": "أنشئ مجموعة واربطها بمركز وحدد مجموعة واتساب وأيام الدوام.",
		"editDescription": "حدّث بيانات المجموعة ومركزها ومجموعة واتساب وأيام الدوام.",
		"deleteConfirm": "حذف المجموعة \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteGroup": "حذف المجموعة"
	},
	students: {
		"title": "الطلاب",
		"tableTitle": "جدول الطلاب",
		"searchStudents": "بحث الطلاب",
		"createStudent": "إنشاء طالب",
		"editStudent": "تعديل طالب",
		"newStudent": "طالب جديد",
		"studentName": "اسم الطالب",
		"firstName": "الاسم الأول",
		"secondName": "اسم الأب",
		"middleName": "اسم الجد",
		"lastName": "اسم العائلة",
		"idNumber": "الرقم الوطني",
		"parentPhone": "هاتف ولي الأمر",
		"phone": "الهاتف",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneOneRequired": "يجب إدخال رقم هاتف واحد على الأقل.",
		"phoneErrorInvalid": "رقم غير صالح.",
		"phoneErrorInvalidCountryCode": "مفتاح الدولة غير صالح.",
		"phoneErrorTooShort": "الرقم قصير جدًا.",
		"phoneErrorTooLong": "الرقم طويل جدًا.",
		"phoneErrorInvalidLength": "طول الرقم غير صالح.",
		"dateOfBirth": "تاريخ الميلاد",
		"group": "المجموعة",
		"groups": "المجموعات",
		"plan": "الخطة",
		"currentPlanPoint": "نقطة الخطة الحالية",
		"maxDailyWeight": "الحد الافتراضي للوزن",
		"dailyWeightLimits": "حدود الوزن حسب أيام الدوام",
		"pointsBalance": "رصيد النقاط",
		"admin": "المسؤول",
		"status": "الحالة",
		"statusActive": "فعال",
		"statusInactive": "غير فعال",
		"statusFrozen": "مجمّد",
		"freezeStudent": "تجميد الطالب",
		"unfreezeStudent": "فك تجميد الطالب",
		"freezeFrom": "من تاريخ",
		"freezeTo": "إلى تاريخ",
		"freezeReason": "سبب التجميد",
		"freezeContactPhone": "رقم التواصل",
		"freezeFailed": "تعذر تجميد هذا الطالب.",
		"frozenSuccess": "تم تجميد الطالب بنجاح.",
		"unfreezeConfirm": "فك تجميد الطالب \"{name}\"؟",
		"unfreezeFailed": "تعذر فك تجميد هذا الطالب.",
		"unfrozenSuccess": "تم فك تجميد الطالب بنجاح.",
		"congratulatory": "رسالة تهنئة",
		"congratulatoryReason": "نص الرسالة",
		"sendCongratulatory": "إرسال التهنئة",
		"congratulatoryFailed": "تعذر إرسال رسالة التهنئة.",
		"congratulatorySent": "تم إرسال رسالة التهنئة بنجاح.",
		"exportStudents": "استخراج الطلاب",
		"importStudents": "ادخال الطلاب",
		"filterByCenter": "تصفية حسب المركز",
		"filterByGroup": "تصفية حسب المجموعة",
		"filterByPlan": "تصفية حسب الخطة",
		"filterByAdmin": "تصفية حسب المسؤول",
		"filterByStatus": "تصفية حسب الحالة",
		"clearFilters": "مسح الفلاتر",
		"exportNow": "استخراج",
		"importNow": "ادخال",
		"importFile": "ملف XLSX",
		"importFileRequired": "يرجى اختيار ملف XLSX.",
		"importHint": "استخدم ملف XLSX بنفس أعمدة ملف الاستخراج، وضع معرّفات المجموعات في group_ids مفصولة بفواصل مثل 2,5,9.",
		"importFailed": "تعذر ادخال الطلاب.",
		"importSuccess": "تم ادخال الطلاب بنجاح.",
		"importReport": "تقرير إدخال الطلاب",
		"importUpdated": "تم تحديثهم",
		"importSkipped": "تم تجاوزهم",
		"importLine": "السطر",
		"importSkipReason": "سبب التجاوز",
		"createdAt": "تاريخ الإنشاء",
		"noGroupsForCenter": "لا توجد مجموعات للمركز المختار.",
		"createDescription": "أضف طالبًا واربطه بالمركز والمجموعات والخطة.",
		"editDescription": "حدّث بيانات الطالب.",
		"deleteConfirm": "حذف الطالب \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteStudent": "حذف الطالب"
	},
	certificates: {
		"title": "الشهادات",
		"studentCertificates": "شهادات الطالب",
		"manageStudentCertificates": "إدارة شهادات الطالب",
		"backToStudents": "العودة إلى الطلاب",
		"availableTitle": "شهادات متاحة للإصدار",
		"availableHint": "تظهر هنا نقاط الشهادة التي وصل إليها الطالب أو تجاوزها ولم تُصدر بعد.",
		"issuedTitle": "الشهادات الصادرة",
		"issuedHint": "سجل ثابت لكل الشهادات التي صدرت لهذا الطالب.",
		"planCheckpoint": "نقطة الخطة",
		"achievementType": "نوع الإنجاز",
		"achievementName": "الإنجاز",
		"achievement": "الإنجاز",
		"achievementDate": "تاريخ الإنجاز",
		"number": "رقم الشهادة",
		"issuedAt": "صدرت بتاريخ",
		"issuedBy": "أصدرها",
		"status": "الحالة",
		"issue": "إصدار الشهادة",
		"issueNow": "إصدار الآن",
		"issueSuccess": "تم إصدار الشهادة بنجاح.",
		"issueFailed": "تعذر إصدار الشهادة.",
		"redesign": "إعادة تصميم الشهادة",
		"redesignNow": "تطبيق التصميم والمحتوى الحاليين",
		"redesignSuccess": "تم تطبيق التصميم وقالب المحتوى الحاليين على الشهادة بنجاح.",
		"redesignFailed": "تعذر إعادة تصميم الشهادة.",
		"redesignConfirmTitle": "تأكيد إعادة تصميم الشهادة",
		"redesignConfirmMessage": "سيُطبّق التصميم وقالب المحتوى الفعليان حاليًا بحسب المركز ونوع الإنجاز على هذه الشهادة.",
		"redesignPreservesContent": "لن يتغيّر رقم الشهادة أو اسم الطالب أو الإنجاز أو التواريخ؛ سيتغيّر التصميم وقالب المحتوى وظهور هوية المركز وفق الإعدادات الحالية.",
		"revoke": "إلغاء الشهادة",
		"revokeNow": "إلغاء الشهادة الآن",
		"revokeSuccess": "تم إلغاء الشهادة مع الاحتفاظ بسجلها.",
		"revokeFailed": "تعذر إلغاء الشهادة.",
		"revokeConfirmTitle": "تأكيد إلغاء الشهادة",
		"revokeConfirmMessage": "ستبقى الشهادة محفوظة، لكن صفحة التحقق العامة ستعرض أنها ملغاة.",
		"revokeReason": "سبب الإلغاء الداخلي",
		"revokeReasonPlaceholder": "اكتب سببًا واضحًا للإلغاء...",
		"revokeReasonPrivacy": "هذا السبب داخلي ولن يظهر في صفحة التحقق العامة.",
		"preview": "معاينة الشهادة",
		"downloadPdf": "تنزيل PDF",
		"noAvailable": "لا توجد شهادات جديدة متاحة؛ قد تكون كل نقاط الشهادة التي وصل إليها الطالب قد صدرت.",
		"noProgress": "لم يبدأ الطالب بالخطة بعد، لذلك لا توجد شهادة متاحة.",
		"noIssued": "لم تصدر أي شهادة لهذا الطالب بعد.",
		"notStarted": "لم يبدأ بعد",
		"viewOnlyNotice": "يمكنك مشاهدة الشهادات، لكن إصدار شهادة جديدة يحتاج صلاحية تعديل الطلاب.",
		"confirmTitle": "تأكيد إصدار الشهادة",
		"confirmMessage": "سيتم حفظ شهادة جديدة للطالب {name} ولا يمكن إصدار نفس نقطة الخطة مرتين."
	},
	certificateDesign: /* @__PURE__ */ JSON.parse("{\"title\":\"تصميم الشهادات\",\"description\":\"خصّص إطار الشهادة وخطها وألوانها لكل مركز ولكل نوع شهادة بصورة مستقلة.\",\"open\":\"تصميم الشهادات\",\"save\":\"حفظ تصميم المركز\",\"saved\":\"تم الحفظ\",\"readOnly\":\"يمكنك معاينة تصاميم الشهادات، لكن تعديلها يحتاج إلى صلاحية تحديث إعدادات الشهادات.\",\"validationError\":\"تعذر حفظ بعض الإعدادات. راجع الحقول المعلّمة ثم حاول مرة أخرى.\",\"contextTitle\":\"الشهادة التي تعدّلها\",\"contextHint\":\"اختر المركز ونوع الشهادة. يُحفظ لكل مركز ثلاثة تصاميم مستقلة، بينما يُؤخذ نوع الطلاب وصياغة النص تلقائيًا من إعدادات المركز.\",\"studentGender\":\"نوع طلاب المركز\",\"previewCenter\":\"المركز\",\"previewCenterHint\":\"اختر المركز الذي تريد تعديل تصميم شهاداته؛ سيُحفظ التعديل لهذا المركز فقط.\",\"selectPreviewCenter\":\"اختر مركزًا\",\"searchPreviewCenter\":\"ابحث باسم المركز\",\"noMatchingPreviewCenter\":\"لا يوجد مركز مطابق للبحث.\",\"noPreviewCenters\":\"لا يوجد مركز حاليًا. أضف مركزًا لإكمال المعاينة وتنزيل PDF.\",\"centerSettingsApplied\":\"هذا هو سياق الحفظ الحالي. اسم الشهادة ونوع الطلاب وصياغة النص وإعداد التوقيع مأخوذة تلقائيًا من المركز.\",\"centerIdentityVisible\":\"هوية ظاهرة\",\"centerIdentityHidden\":\"هوية مخفية\",\"certificateType\":\"نوع الشهادة\",\"previewAchievement\":\"إنجاز المعاينة\",\"previewAchievementHint\":\"اختر نقطة شهادة حقيقية من الخطط لعرض اسم الإنجاز كما سيظهر في الشهادة.\",\"searchPreviewAchievement\":\"ابحث باسم الإنجاز أو الخطة أو النقطة\",\"noMatchingPreviewAchievement\":\"لا توجد نتيجة مطابقة للبحث.\",\"noPreviewAchievements\":\"لا توجد نقطة شهادة من هذا النوع في الخطط حاليًا. أضف بيانات الإنجاز إلى نقطة خطة لتظهر هنا.\",\"matrixTitle\":\"تصاميم أنواع الشهادات\",\"matrixHint\":\"لكل مركز ثلاثة تصاميم: سورة، جزء، وثلاثة أجزاء. النقطة البرتقالية تعني وجود تعديل غير محفوظ.\",\"configurationsCount\":\"{count} تصاميم\",\"unsaved\":\"تغييرات غير محفوظة\",\"themeTitle\":\"القالب والإطار\",\"editingContext\":\"تعديل تصميم {center} · {type}\",\"themeCountLabel\":\"قالب\",\"typographyAndColors\":\"الخطوط والألوان\",\"typographyAndColorsHint\":\"اختر خطًا عربيًا واضحًا، ثم عدّل ألوان النصوص أو استعد ألوان القالب الأصلية.\",\"font\":\"خط الشهادة\",\"invalidColor\":\"أدخل لونًا سداسيًا صحيحًا مثل #0F537F.\",\"restoreThemeColors\":\"استعادة ألوان القالب\",\"livePreview\":\"معاينة فورية\",\"previewHint\":\"تتحدث المعاينة مباشرة عند تغيير المركز أو نوع الشهادة أو الإطار أو الخط أو الألوان.\",\"downloadPreviewPdf\":\"تنزيل PDF للمعاينة\",\"previewPdfFailed\":\"تعذر إنشاء ملف PDF للمعاينة الحالية.\",\"noTheme\":\"بدون قالب\",\"noFont\":\"بدون خط\",\"a4Landscape\":\"A4 أفقي\",\"unsavedChanges\":\"توجد تغييرات غير محفوظة. اختر المركز المعلّم بالنقطة البرتقالية ثم احفظ تصميمه.\",\"allSaved\":\"جميع تصاميم المراكز محفوظة.\",\"workspace\":{\"label\":\"أقسام إعداد الشهادة\",\"design\":\"المظهر والتصميم\",\"content\":\"محتوى الشهادة\"},\"content\":{\"title\":\"قوالب محتوى الشهادة\",\"description\":\"حرّر صياغة الشهادة واربط القالب المناسب بالمركز أو نوع الإنجاز.\",\"pageDescription\":\"أنشئ قوالب احترافية لمحتوى الشهادة، استخدم المتغيرات الآمنة، وحدد القالب المناسب لكل مركز ونوع شهادة.\",\"contextTitle\":\"سياق المحتوى والمعاينة\",\"contextHint\":\"اختر المركز ونوع الشهادة والإنجاز لمشاهدة القالب الفعلي وتحريره ضمن السياق الصحيح.\",\"readOnly\":\"يمكنك معاينة محتوى الشهادات والقوالب المستخدمة، لكن تعديل الربط يحتاج إلى صلاحية تحديث إعدادات الشهادات.\",\"previewHint\":\"تتحدث المعاينة مباشرة أثناء تحرير أقسام القالب أو تغيير المركز ونوع الشهادة والإنجاز.\",\"effectiveTemplate\":\"القالب المستخدم حاليًا\",\"legacyTemplate\":\"الصياغة الافتراضية القديمة\",\"systemTemplate\":\"قالب نظام\",\"protectedTemplate\":\"قالب محمي من الحذف\",\"systemCannotDelete\":\"قوالب النظام محمية ولا يمكن حذفها.\",\"applyCurrentContext\":\"تطبيق على المركز والنوع الحالي\",\"templateLibrary\":\"مكتبة القوالب\",\"templateLibraryHint\":\"اختر قالبًا لمعاينته وتعديله، أو أنشئ نسخة خاصة قبل تخصيصه.\",\"searchTemplates\":\"ابحث باسم القالب\",\"noTemplates\":\"لا توجد قوالب محتوى بعد.\",\"noMatchingTemplates\":\"لا يوجد قالب مطابق للبحث.\",\"newTemplate\":\"قالب جديد\",\"createTemplate\":\"إنشاء القالب\",\"editTemplate\":\"تعديل القالب\",\"duplicateTemplate\":\"إنشاء نسخة\",\"copyName\":\"نسخة من {name}\",\"saveTemplate\":\"حفظ القالب\",\"deleteTemplate\":\"حذف القالب\",\"templateCreated\":\"تم إنشاء قالب محتوى الشهادة.\",\"templateUpdated\":\"تم حفظ تعديلات قالب الشهادة.\",\"templateDeleted\":\"تم حذف قالب محتوى الشهادة.\",\"deleteFailed\":\"تعذر حذف قالب محتوى الشهادة.\",\"confirmDeleteTemplate\":\"هل تريد حذف قالب «{name}»؟ لا يمكن التراجع عن هذه العملية.\",\"confirmDiscard\":\"لديك تعديلات غير محفوظة. هل تريد تجاهلها والمتابعة؟\",\"discardChanges\":\"تجاهل التعديلات\",\"editorHint\":\"يظهر كل قسم في موضعه المخصص داخل الشهادة والمعاينة وملف PDF.\",\"templateReadOnly\":\"يمكنك قراءة القالب واستخدامه، لكن تعديل تعريف القوالب يحتاج إلى صلاحية إدارة قوالب المحتوى.\",\"templateName\":\"اسم القالب\",\"templateNamePlaceholder\":\"مثال: قالب دار القرآن الخاص\",\"templateActive\":\"القالب فعّال\",\"templateActiveHint\":\"متاح للربط\",\"assignmentsCount\":\"{count} ربط\",\"availableVariables\":\"المتغيرات المتاحة\",\"variablesHint\":\"ضع المؤشر داخل القسم المطلوب ثم اضغط المتغير لإدراجه في موضع المؤشر.\",\"safeRenderingHint\":\"يُعرض النص بأمان دون تشغيل HTML أو شيفرات داخل الشهادة.\",\"assignmentTitle\":\"نطاق استخدام القالب\",\"assignmentHint\":\"حدد أين يُستخدم القالب. إعداد المركز والنوع هو الأكثر أولوية من القوالب العامة.\",\"assignmentTemplate\":\"القالب المطلوب تطبيقه\",\"assignmentScope\":\"نطاق التطبيق\",\"assignmentAchievementType\":\"نوع الشهادة\",\"assignmentCenter\":\"المركز\",\"assignmentGender\":\"نوع الطلاب\",\"allAchievementTypes\":\"جميع أنواع الشهادات\",\"saveAssignment\":\"حفظ الربط\",\"updateAssignment\":\"تحديث الربط\",\"removeAssignment\":\"إزالة الربط\",\"confirmRemoveAssignment\":\"هل تريد إزالة هذا الربط؟ سيعود النظام تلقائيًا إلى القالب التالي حسب الأولوية.\",\"existingAssignment\":\"هذا النطاق مرتبط حاليًا بقالب «{name}».\",\"assignmentSaved\":\"تم حفظ ربط قالب الشهادة.\",\"assignmentRemoved\":\"تمت إزالة ربط قالب الشهادة.\",\"assignmentFailed\":\"تعذر حفظ ربط قالب الشهادة.\",\"assignmentRemoveFailed\":\"تعذر إزالة ربط قالب الشهادة.\",\"noActiveTemplates\":\"لا يوجد قالب فعّال يمكن ربطه. فعّل قالبًا أو أنشئ قالبًا جديدًا أولًا.\",\"requestFailed\":\"تعذر حفظ التغييرات. راجع الحقول وحاول مرة أخرى.\",\"scopes\":{\"global\":\"جميع المراكز\",\"gender\":\"حسب نوع الطلاب\",\"center\":\"مركز محدد\"},\"sources\":{\"center_type\":\"مخصص للمركز ونوع الشهادة\",\"center_all\":\"مخصص للمركز وكل الأنواع\",\"gender_type\":\"حسب نوع الطلاب ونوع الشهادة\",\"gender_all\":\"حسب نوع الطلاب\",\"global_type\":\"عام لنوع الشهادة\",\"global_all\":\"القالب العام\",\"legacy\":\"الصياغة الافتراضية القديمة\"},\"variables\":{\"studentName\":\"اسم الطالب\",\"centerName\":\"اسم المركز في الشهادة\",\"achievementLabel\":\"نوع الإنجاز\",\"achievementName\":\"اسم الإنجاز\",\"planName\":\"اسم الخطة\",\"planPointName\":\"اسم نقطة الخطة\",\"hijriDate\":\"التاريخ الهجري\",\"gregorianDate\":\"التاريخ الميلادي\",\"certificateNumber\":\"رقم الشهادة\"},\"variableDescriptions\":{\"studentName\":\"الاسم الكامل للطالب أو الطالبة كما حُفظ وقت الإصدار.\",\"centerName\":\"الاسم المعتمد للمركز على الشهادات.\",\"achievementLabel\":\"سورة أو جزء أو ثلاثة أجزاء بحسب نوع الشهادة.\",\"achievementName\":\"اسم السورة أو الجزء المحفوظ في نقطة الخطة.\",\"planName\":\"اسم الخطة المرتبطة بالطالب عند الإصدار.\",\"planPointName\":\"اسم نقطة الإنجاز في الخطة.\",\"hijriDate\":\"تاريخ الإنجاز الهجري المثبت في الشهادة.\",\"gregorianDate\":\"تاريخ الإنجاز الميلادي المثبت في الشهادة.\",\"certificateNumber\":\"الرقم الفريد للشهادة الصادرة.\"},\"sections\":{\"title\":{\"label\":\"عنوان الشهادة\",\"hint\":\"العنوان الرئيسي الظاهر أعلى الشهادة.\"},\"quote_first\":{\"label\":\"الشطر الأول من بيت الشعر\",\"hint\":\"يظهر في الجهة الأولى من الزخرفة الوسطية.\"},\"quote_second\":{\"label\":\"الشطر الثاني من بيت الشعر\",\"hint\":\"يظهر مقابل الشطر الأول حول الزخرفة.\"},\"intro\":{\"label\":\"مقدمة التهنئة\",\"hint\":\"أدخل اسم المركز بمتغير المركز ليُستبدل تلقائيًا.\"},\"student_line\":{\"label\":\"سطر اسم الطالب\",\"hint\":\"ضع متغير اسم الطالب ويمكنك إحاطته بالزخارف مثل ﴿ ﴾.\"},\"achievement_line\":{\"label\":\"سطر الإنجاز\",\"hint\":\"استخدم متغيري نوع الإنجاز واسمه ليعمل القالب مع جميع أنواع الشهادات.\"},\"closing\":{\"label\":\"الدعاء والخاتمة\",\"hint\":\"النص الختامي الظاهر قبل التوقيعات والتاريخ.\"}},\"validation\":{\"nameRequired\":\"أدخل اسمًا واضحًا للقالب.\",\"sectionRequired\":\"هذا القسم مطلوب ولا يمكن تركه فارغًا.\",\"requiredVariable\":\"يجب أن يحتوي هذا القسم على المتغير {variable}.\",\"plainTextOnly\":\"استخدم نصًا عاديًا ومتغيرات القالب فقط؛ لا يُسمح بوسوم HTML أو أوامر Blade.\",\"unknownVariables\":\"يوجد متغير غير معروف: {variables}\",\"recommendedVariables\":\"المتغيرات التالية مطلوبة في أقسامها: {variables}\"}},\"genders\":{\"male\":\"ذكور\",\"female\":\"إناث\"},\"types\":{\"surah\":\"سورة\",\"part\":\"جزء\",\"three_parts\":\"ثلاثة أجزاء\"},\"themes\":{\"blue\":\"أزرق وذهبي\",\"emerald\":\"زمردي وذهبي\",\"burgundy\":\"عنّابي وذهبي\",\"navy\":\"كحلي وذهبي\",\"purple\":\"بنفسجي وذهبي\",\"black\":\"أسود وذهبي\",\"turquoise\":\"تركواز وذهبي\",\"rose\":\"وردي غباري\",\"bronze\":\"برونزي وذهبي\",\"royal\":\"أزرق ملكي وذهبي\",\"indigo\":\"نيلي وذهبي\",\"crimson\":\"قرمزي وذهبي\",\"coral\":\"مرجاني وذهبي\",\"orange\":\"برتقالي وذهبي\",\"copper\":\"نحاسي\",\"olive\":\"زيتوني وذهبي\",\"forest\":\"أخضر غابة وذهبي\",\"slate\":\"رمادي أردوازي\",\"lavender\":\"لافندر وذهبي\",\"mint\":\"نعناعي وذهبي\"},\"fonts\":{\"classic\":\"كلاسيكي — نسخ وأميري\",\"amiri\":\"أميري\",\"naskh\":\"نسخ عربي\",\"kufi\":\"كوفي عربي\",\"sans_arabic\":\"عربي عصري\",\"naskh_kufi\":\"نسخ مع عناوين كوفية\",\"naskh_nastaliq\":\"نسخ مع عناوين نستعليق\",\"sans_amiri\":\"عصري مع عناوين أميري\",\"sans_kufi\":\"عصري مع عناوين كوفية\",\"sans_naskh\":\"عصري مع عناوين نسخ\",\"kufi_amiri\":\"كوفي مع عناوين أميري\",\"sans_nastaliq\":\"عصري مع عناوين نستعليق\"},\"colors\":{\"heading\":\"لون العنوان\",\"studentName\":\"لون اسم الطالب\",\"content\":\"لون النص الأساسي\",\"accent\":\"لون الزخارف والإبراز\"},\"preview\":{\"studentNames\":{\"male\":\"مُحَمَّد أَحْمَد العَبْدُ الله\",\"female\":\"مَرْيَم أَحْمَد العَبْدُ الله\"},\"centerLogo\":\"المركز\",\"projectLogo\":\"المشروع\",\"centerManager\":\"توقيع مدير المركز\",\"projectManager\":\"توقيع مدير المشروع\",\"achievementDate\":\"تاريخ الإنجاز\"}}"),
	evaluations: {
		"title": "التقييمات",
		"tableTitle": "جدول التقييمات",
		"searchEvaluations": "بحث التقييمات",
		"createEvaluation": "إضافة تقييم",
		"editEvaluation": "تعديل تقييم",
		"newEvaluation": "تقييم جديد",
		"createDescription": "اختر المركز والمجموعة والتاريخ ثم أدخل تقييمات الطلاب.",
		"editDescription": "عدّل درجات وحضور الطلاب لهذا التقييم.",
		"scoreFieldMode": "حقل التقييم",
		"center": "المركز",
		"group": "المجموعة",
		"date": "التاريخ",
		"student": "الطالب",
		"attendance": "الحضور",
		"present": "حاضر",
		"excusedAbsence": "غائب بعذر",
		"absence": "غائب بدون عذر",
		"exempt": "معفى",
		"alhifz": "الحفظ",
		"warud": "الورد",
		"akhlaqi": "الأخلاق",
		"tajwid": "التجويد",
		"note": "ملاحظة",
		"loadStudents": "تحميل الطلاب",
		"studentsList": "قائمة الطلاب",
		"studentsHint": "يمكن تعديل حالة الحضور ودرجات كل طالب قبل الحفظ.",
		"noStudentsLoaded": "اختر مركزًا ومجموعة وتاريخًا ثم حمّل الطلاب.",
		"alreadyExists": "يوجد تقييم مسجل لهذه المجموعة في نفس التاريخ.",
		"openExisting": "فتح التقييم الحالي",
		"status": "تنبيهات الغياب",
		"alertsPending": "غير مرسلة",
		"alertsSent": "مرسلة",
		"createdAt": "تاريخ الإنشاء",
		"openReport": "فتح تقرير التقييم",
		"sendAlerts": "إرسال تنبيهات الغياب",
		"sendAlertsConfirm": "إرسال تنبيهات الغياب لهذا التقييم الآن؟",
		"sendAlertsFailed": "تعذر إرسال تنبيهات الغياب.",
		"filters": {
			"toggle": "فلتر",
			"toggleWithCount": "فلتر ({count})",
			"center": "المركز",
			"group": "المجموعة",
			"dateFrom": "من تاريخ",
			"dateTo": "إلى تاريخ",
			"alertStatus": "حالة تنبيهات الغياب",
			"apply": "تطبيق الفلاتر",
			"clear": "مسح الفلاتر"
		},
		"preview": {
			"title": "معاينة رسائل الغياب",
			"open": "عرض رسائل الغياب المنشأة",
			"status": "معاينة محلية",
			"localOnlyTitle": "وضع محلي:",
			"localOnlyDescription": "هذه الرسائل محفوظة للمعاينة فقط ولم تُرسل إلى واتساب.",
			"empty": "لا توجد رسائل غياب منشأة لهذا التقييم.",
			"loadFailed": "تعذر تحميل رسائل المعاينة.",
			"recipients": "المستلمون",
			"occurrence": "رقم التكرار",
			"centerGroup": "مجموعة التقييم"
		},
		"messageLog": {
			"title": "سجل رسائل الغياب",
			"open": "عرض سجل الرسائل",
			"empty": "لا توجد رسائل غياب مسجلة لهذا التقييم.",
			"loadFailed": "تعذر تحميل سجل الرسائل.",
			"evaluationDetails": "تفاصيل التقييم",
			"executionTime": "وقت التنفيذ",
			"action": "الإجراء",
			"resend": "إعادة إرسال",
			"resendSuccess": "تمت إعادة إرسال الرسالة.",
			"resendFailed": "تعذرت إعادة إرسال الرسالة.",
			"reviewRequired": "تحتاج نتيجة الإرسال إلى مراجعة يدوية، لذلك أوقفت إعادة الإرسال لمنع التكرار.",
			"noContent": "لم يتم تسجيل نص رسالة.",
			"statuses": {
				"sent": "مرسلة",
				"localPreview": "معاينة محلية",
				"failed": "فشلت",
				"notSent": "غير مرسلة"
			},
			"actions": {
				"sendMessage": "إرسال رسالة",
				"sendMessageAndFreeze": "إرسال رسالة وتجميد",
				"freezeStudent": "تجميد الطالب",
				"dismissStudent": "فصل الطالب"
			}
		},
		"deleteConfirm": "حذف تقييم مجموعة {group} في مركز {center} بتاريخ {date}؟",
		"deleteEvaluation": "حذف التقييم",
		"deleted": "تم حذف التقييم بنجاح.",
		"deleteFailed": "تعذر حذف التقييم."
	},
	homeworks: {
		"title": "الواجبات",
		"tableTitle": "جدول الواجبات",
		"searchHomeworks": "بحث الواجبات",
		"createHomework": "إضافة واجب",
		"editHomework": "تعديل واجب",
		"newHomework": "واجب جديد",
		"createDescription": "اختر المركز والمجموعة والتاريخ ثم حمّل الطلاب وحدد النقاط المكتملة.",
		"editDescription": "عدّل النقاط غير المحتسبة واحفظ الواجب.",
		"center": "المركز",
		"group": "المجموعة",
		"date": "التاريخ",
		"student": "الطالب",
		"studentsList": "قائمة الطلاب",
		"studentsHint": "لكل طالب تظهر عشرون خانة من نقاط الخطة التالية له.",
		"searchStudent": "بحث باسم الطالب",
		"searchStudentPlaceholder": "ابحث باسم الطالب...",
		"noStudentSearchResults": "لا يوجد طلاب بهذا الاسم.",
		"noStudentsLoaded": "اختر مركزًا ومجموعة وتاريخًا ثم حمّل الطلاب.",
		"loadStudents": "تحميل الطلاب",
		"exportPdf": "تصدير PDF",
		"groupWorkingDaysHint": "الأيام المسموحة حسب دوام المجموعة: {days}",
		"alreadyExists": "يوجد واجب مسجل لهذه المجموعة في نفس التاريخ.",
		"openExisting": "فتح الواجب الحالي",
		"progress": "آخر نقطة وصل لها الطالب",
		"currentPosition": "آخر نقطة وصل لها الطالب",
		"notStarted": "لم يبدأ بعد",
		"nextPoints": "النقاط التالية",
		"noPlanPoints": "لا توجد نقاط متاحة لهذا الطالب.",
		"pointValue": "{points} نقطة",
		"done": "تم",
		"awarded": "محتسبة",
		"nextHomework": "للمرة القادمة",
		"previousNextHomework": "مطلوب سابقًا",
		"balance": "الرصيد",
		"pointsAdjustment": "تعديل الرصيد",
		"pointsAdjustmentHint": "اكتب رقمًا موجبًا للزيادة أو سالبًا للنقصان.",
		"balanceAfterAdjustment": "بعد التعديل",
		"manualAdjustmentsTotal": "إجمالي التعديلات اليدوية: {points}",
		"selectedPointsTotal": "إجمالي النقاط المحددة: {points}",
		"studentsCount": "عدد الطلاب",
		"completedPointsCount": "النقاط المكتملة",
		"createdAt": "تاريخ الإنشاء",
		"pointsHistory": "سجل النقاط",
		"historyDate": "التاريخ",
		"planPoint": "نقطة الخطة",
		"points": "النقاط",
		"balanceAfter": "الرصيد بعد",
		"noHistory": "لا يوجد سجل نقاط لهذا الطالب.",
		"historyFailed": "تعذر تحميل سجل النقاط.",
		"deleteConfirm": "حذف واجب مجموعة {group} في مركز {center} بتاريخ {date}؟",
		"deleteHomework": "حذف الواجب",
		"deleted": "تم حذف الواجب بنجاح.",
		"deleteFailed": "تعذر حذف الواجب."
	},
	absenceRules: {
		"title": "قواعد الغياب",
		"tableTitle": "جدول قواعد الغياب",
		"searchRules": "بحث قواعد الغياب",
		"createRule": "إنشاء قاعدة غياب",
		"editRule": "تعديل قاعدة غياب",
		"newRule": "قاعدة غياب جديدة",
		"center": "المركز",
		"allCenters": "كل المراكز",
		"centerOptionalHint": "اتركه فارغًا لتطبيق القاعدة على كل المراكز.",
		"attendanceType": "نوع الغياب",
		"attendanceAbsence": "غياب بدون عذر",
		"attendanceExcusedAbsence": "غياب بعذر",
		"occurrenceNumber": "رقم التكرار الشهري",
		"occurrenceMonthlyHint": "مثال: 3 يعني ثالث غياب لنفس الطالب داخل نفس الشهر.",
		"action": "الإجراء",
		"actionSendMessage": "تنبيه فقط",
		"actionFreezeStudent": "تجميد الطالب",
		"actionDismissStudent": "فصل الطالب",
		"deductionPointsCount": "عدد نقاط الخصم",
		"messageTemplate": "قالب الرسالة",
		"noTemplate": "بدون قالب",
		"freezeReason": "سبب التجميد",
		"freezeWorkingDays": "عدد أيام الدوام للتجميد",
		"sendToCenterGroup": "الإرسال أيضًا إلى مجموعة التقييم",
		"isActive": "فعّال",
		"status": "الحالة",
		"active": "فعال",
		"inactive": "غير فعال",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "حدّد نوع الغياب والتكرار ثم اختر الإجراء وحدد نقاط الخصم إن وجدت.",
		"editDescription": "حدّث شروط القاعدة أو الإجراء المرتبط بها.",
		"deleteConfirm": "حذف قاعدة الغياب لـ \"{center}\" (تكرار {occurrence})؟",
		"deleteRule": "حذف القاعدة",
		"deleted": "تم حذف قاعدة الغياب بنجاح.",
		"deleteFailed": "تعذر حذف قاعدة الغياب."
	},
	messageTemplates: {
		"title": "قوالب الرسائل",
		"tableTitle": "جدول قوالب الرسائل",
		"searchTemplates": "بحث قوالب الرسائل",
		"createTemplate": "إنشاء قالب رسالة",
		"editTemplate": "تعديل قالب رسالة",
		"newTemplate": "قالب رسالة جديد",
		"templateName": "اسم القالب",
		"key": "المفتاح",
		"locale": "اللغة",
		"localeArabic": "العربية",
		"localeEnglish": "الإنجليزية",
		"content": "محتوى الرسالة",
		"placeholdersHint": "يمكن استخدام متغيّرات مثل: student.full_name و evaluation.date_ar و freeze.reason و rule.deduction_points_count",
		"isActive": "فعّال",
		"status": "الحالة",
		"active": "فعال",
		"inactive": "غير فعال",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أنشئ قالبًا عامًا باسم ومفتاح واضح لاستخدامه في النظام.",
		"editDescription": "حدّث نص القالب والمتغيّرات المستخدمة.",
		"deleteConfirm": "حذف قالب الرسالة \"{name}\"؟",
		"deleteTemplate": "حذف القالب",
		"deleted": "تم حذف قالب الرسالة بنجاح.",
		"deleteFailed": "تعذر حذف قالب الرسالة."
	},
	days: {
		"sunday": "الأحد",
		"monday": "الاثنين",
		"tuesday": "الثلاثاء",
		"wednesday": "الأربعاء",
		"thursday": "الخميس",
		"friday": "الجمعة",
		"saturday": "السبت"
	},
	activityLogs: {
		"title": "سجل النشاط",
		"tableTitle": "سجل النشاط",
		"searchLogs": "بحث في السجل",
		"historyFor": "سجل: {name}",
		"noHistory": "لا يوجد سجل نشاط لهذا العنصر.",
		"noChanges": "لا توجد تغييرات قبل/بعد لهذا الحدث.",
		"field": "الحقل",
		"before": "قبل",
		"after": "بعد",
		"by": "بواسطة",
		"description": "الوصف",
		"event": "الحدث",
		"subject": "العنصر",
		"causer": "المنفّذ",
		"createdAt": "تاريخ الإنشاء"
	},
	dashboard: {
		"title": "لوحة التحكم",
		"eyebrow": "نظرة مباشرة",
		"subtitle": "متابعة مترابطة للطلاب، الحضور، الواجبات، المراكز، وحالة واتساب.",
		"empty": "لا توجد بيانات بعد.",
		"percentValue": "{value}٪",
		"summaryStrip": {
			"ariaLabel": "ملخص لوحة التحكم",
			"centers": "{count} مركز",
			"groups": "{count} مجموعة",
			"plans": "{count} خطة",
			"whatsapp": "{connected}/{total} واتساب"
		},
		"metrics": {
			"students": "الطلاب",
			"studentsSubtitle": "{active} فعال، {frozen} مجمّد",
			"attendanceRate": "نسبة الحضور",
			"attendanceSubtitle": "{present} حضور من أصل {total} خلال 30 يوم",
			"homeworkPoints": "نقاط الواجبات",
			"homeworkSubtitle": "{points} نقطة ممنوحة عبر {count} واجب هذا الشهر",
			"evaluations": "تقييمات الشهر",
			"evaluationsSubtitle": "{centers} مركز و {groups} مجموعة"
		},
		"charts": {
			"attendanceTrend": "اتجاه الحضور",
			"attendanceTrendSubtitle": "آخر 14 يوم حسب سجلات التقييم",
			"studentStatus": "حالة الطلاب",
			"studentStatusSubtitle": "توزيع الطلاب حسب الحالة الحالية",
			"homeworkProgress": "إنجاز الواجبات",
			"homeworkProgressSubtitle": "آخر واجبات مسجلة، منجز مقابل متبقّي"
		},
		"statuses": {
			"active": "فعال",
			"frozen": "مجمّد",
			"inactive": "غير فعال"
		},
		"attendance": {
			"present": "حضور",
			"absent": "غياب",
			"excused": "غياب بعذر"
		},
		"homeworks": {
			"completed": "منجز",
			"pending": "متبقّي"
		},
		"alerts": {
			"title": "المؤشرات",
			"subtitle": "نقاط تحتاج متابعة تشغيلية",
			"studentsWithoutPlan": {
				"title": "طلاب بدون خطة",
				"description": "{count} طالب يحتاج ربط خطة"
			},
			"studentsWithoutGroup": {
				"title": "طلاب بدون مجموعة",
				"description": "{count} طالب يحتاج ربط مجموعة"
			},
			"failedAbsenceMessages": {
				"title": "رسائل غياب فاشلة",
				"description": "{count} رسالة لم ترسل خلال 30 يوم"
			},
			"recentEvaluations": {
				"title": "تقييمات حديثة",
				"description": "{count} تقييم خلال آخر 7 أيام"
			},
			"whatsappDevices": {
				"title": "أجهزة واتساب",
				"description": "{connected} من {total} أجهزة متصلة"
			}
		},
		"centerPerformance": {
			"title": "أداء المراكز",
			"subtitle": "أكثر المراكز نشاطاً حسب عدد الطلاب",
			"meta": "{active} فعال من {students} طالب، {groups} مجموعة",
			"activityValue": "{evaluations} تقييم / {homeworks} واجب"
		},
		"recentActivity": {
			"title": "آخر النشاط",
			"subtitle": "أحدث التقييمات والواجبات وتنبيهات الغياب"
		},
		"activityTypes": {
			"evaluation": "تقييم",
			"homework": "واجب",
			"absence": "غياب"
		},
		"actions": {
			"title": "إجراءات سريعة",
			"subtitle": "اختصارات لأكثر العمليات اليومية",
			"createStudent": "إضافة طالب",
			"createStudentMeta": "فتح نموذج طالب جديد",
			"createEvaluation": "إضافة تقييم",
			"createEvaluationMeta": "اختيار مركز وتاريخ",
			"createHomework": "إضافة واجب",
			"createHomeworkMeta": "تسجيل تقدم الطلاب"
		}
	},
	whatsapp: {
		"title": "واتساب",
		"description": "إدارة جلسة واتساب وإرسال رسائل اختبار بسرعة.",
		"deviceFallback": "الجهاز الرئيسي",
		"deleteDevice": "حذف الجهاز",
		"deleteConfirm": "حذف الجهاز \"{name}\"؟ هذا سيعيد تعيين الجلسة الحالية.",
		"deviceDeleted": "تم حذف الجهاز بنجاح.",
		"deleteFailed": "تعذر حذف الجهاز.",
		"apiMissing": "واجهة WhatsApp API غير مهيأة.",
		"apiMissingHelp": "أضف WHATSAPP_API_URL (واختياريًا WHATSAPP_API_KEY) في ملف البيئة.",
		"instructionsTitle": "استخدم واتساب على هذا النظام",
		"step1": "افتح واتساب على هاتفك.",
		"step2": "اضغط القائمة في أندرويد أو الإعدادات في iPhone.",
		"step3": "اختر الأجهزة المرتبطة ثم ربط جهاز.",
		"step4": "وجّه هاتفك إلى هذه الشاشة لمسح رمز QR.",
		"scanHint": "يتم تحديث رمز QR تلقائيًا كل 30 ثانية.",
		"refreshNow": "تحديث الآن",
		"connected": "الجهاز متصل. يمكنك إرسال رسالة الآن.",
		"phone": "الهاتف",
		"message": "الرسالة",
		"phonePlaceholder": "962799988888",
		"messagePlaceholder": "تجربة",
		"send": "إرسال",
		"sendSuccess": "تم إرسال الرسالة بنجاح.",
		"sendFailed": "تعذر إرسال رسالة واتساب.",
		"refreshFailed": "تعذر تحديث حالة QR."
	},
	settings: {
		"title": "الإعدادات",
		"branding": "الهوية البصرية",
		"brandingDescription": "تحكم باسم التطبيق والوصف وملفات الهوية المستخدمة في الشريط الجانبي وصفحة الدخول.",
		"brandName": "اسم العلامة",
		"brandTagline": "الوصف المختصر",
		"lightModeLogo": "شعار الوضع الفاتح",
		"darkModeLogo": "شعار الوضع الداكن",
		"appIcon": "أيقونة التطبيق",
		"noLogoUploaded": "لا يوجد شعار مرفوع",
		"uploadLightLogo": "رفع شعار الوضع الفاتح",
		"uploadDarkLogo": "رفع شعار الوضع الداكن",
		"uploadIcon": "رفع الأيقونة",
		"recommendedLogo": "مقترح: شعار بخلفية شفافة بارتفاع يقارب 36px.",
		"recommendedDarkLogo": "استخدم شعارًا فاتح اللون لخلفيات الوضع الداكن.",
		"recommendedIcon": "مقترح: أيقونة مربعة بحجم 48x48 أو 64x64.",
		"currentLightModeLogo": "الشعار الحالي للوضع الفاتح",
		"currentDarkModeLogo": "الشعار الحالي للوضع الداكن",
		"currentAppIcon": "أيقونة التطبيق الحالية",
		"localization": "الترجمة والاتجاه",
		"localizationDescription": "حدّد اللغة الافتراضية واتجاه الواجهة (LTR/RTL).",
		"defaultLanguage": "اللغة الافتراضية",
		"interfaceDirection": "اتجاه الواجهة",
		"dateTime": "التاريخ والوقت",
		"dateTimeDescription": "حدّد المنطقة الزمنية ومعايير التنسيق العامة.",
		"dateFormat": "تنسيق التاريخ",
		"timeFormat": "تنسيق الوقت",
		"timezone": "المنطقة الزمنية",
		"searchTimezone": "ابحث عن المنطقة الزمنية...",
		"appearance": "المظهر",
		"appearanceDescription": "خصّص الوضع وشكل المكونات ولون التمييز للوضع الحالي.",
		"mode": "الوضع",
		"componentShape": "شكل المكونات",
		"sidebarBehavior": "حجم الشريط الجانبي",
		"sidebarDefault": "افتراضي",
		"sidebarCondensed": "مكثف",
		"sidebarHidden": "مخفي",
		"sidebarSmallHoverActive": "صغير مع التوسعة عند المرور (نشط)",
		"sidebarSmallHover": "صغير مع التوسعة عند المرور",
		"fontFamily": "نوع الخط",
		"accentColor": "لون التمييز ({mode})",
		"light": "فاتح",
		"dark": "داكن",
		"compact": "مضغوط",
		"comfortable": "مريح",
		"rounded": "مستدير",
		"accent": "التمييز",
		"english": "الإنجليزية",
		"arabic": "العربية",
		"ltr": "LTR",
		"rtl": "RTL",
		"uploadAppIcon": "رفع أيقونة التطبيق",
		"uploadDarkModeLogo": "رفع شعار الوضع الداكن",
		"uploadLightModeLogo": "رفع شعار الوضع الفاتح"
	},
	uploads: {
		"uploadImage": "رفع صورة",
		"current": "الحالي",
		"selected": "المحدد",
		"selectedPreview": "معاينة الملف المحدد",
		"noImageSet": "لا توجد صورة",
		"noFileSelected": "لم يتم اختيار ملف",
		"allowedFormats": "المسموح: JPG, PNG, WEBP. الحد الأقصى: 2MB.",
		"upload": "رفع",
		"uploadCompleted": "اكتمل الرفع."
	},
	notifications: {
		"settingsSaved": "تم حفظ التغييرات بنجاح.",
		"settingsSavedTitle": "تم حفظ الإعدادات",
		"saveFailedTitle": "فشل الحفظ",
		"saveFailedDetail": "تعذر حفظ الإعدادات. حاول مرة أخرى.",
		"loadFailedTitle": "فشل التحميل",
		"loadFailedDetail": "تعذر تحميل بيانات الجدول. حاول مرة أخرى.",
		"requestFailedTitle": "فشل الطلب",
		"requestFailedDetail": "حدث خطأ ما. حاول مرة أخرى.",
		"deleteFailedTitle": "فشل الحذف",
		"deleteUserFailed": "تعذر حذف هذا المستخدم.",
		"deleteRoleFailed": "تعذر حذف هذا الدور.",
		"deletePlanFailed": "تعذر حذف هذه الخطة.",
		"deleteCenterFailed": "تعذر حذف هذا المركز.",
		"deleteGroupFailed": "تعذر حذف هذه المجموعة.",
		"deleteStudentFailed": "تعذر حذف هذا الطالب.",
		"userDeleted": "تم حذف المستخدم بنجاح.",
		"roleDeleted": "تم حذف الدور بنجاح.",
		"planDeleted": "تم حذف الخطة بنجاح.",
		"centerDeleted": "تم حذف المركز بنجاح.",
		"groupDeleted": "تم حذف المجموعة بنجاح.",
		"studentDeleted": "تم حذف الطالب بنجاح.",
		"imageUploaded": "تم رفع الصورة بنجاح.",
		"uploadFailedTitle": "فشل الرفع",
		"uploadFailedDetail": "تعذر رفع الصورة. استخدم JPG أو PNG أو WEBP بحجم أقل من 2MB."
	},
	errors: {
		"forbidden": {
			"title": "تم رفض الوصول",
			"description": "لا تملك الصلاحية للوصول إلى هذه الصفحة."
		},
		"notFound": {
			"title": "الصفحة غير موجودة",
			"description": "الصفحة المطلوبة غير موجودة."
		},
		"expired": {
			"title": "انتهت الجلسة",
			"description": "انتهت صلاحية الجلسة. حدّث الصفحة وحاول مرة أخرى."
		},
		"serverError": {
			"title": "خطأ في الخادم",
			"description": "حدث خطأ من جهة الخادم. حاول مرة أخرى بعد قليل."
		},
		"unavailable": {
			"title": "الخدمة غير متاحة",
			"description": "الخدمة غير متاحة مؤقتًا. حاول مرة أخرى بعد قليل."
		},
		"actions": {
			"backToDashboard": "العودة إلى لوحة التحكم",
			"backToHome": "العودة إلى الصفحة الرئيسية",
			"tryAgain": "إعادة المحاولة"
		}
	}
};
var en_default = {
	auth: {
		"login": "Login",
		"signIn": "Sign in",
		"useAdminAccount": "Use your admin account to access the dashboard.",
		"email": "Email",
		"password": "Password",
		"rememberMe": "Remember me",
		"appLogoAlt": "{appName} logo"
	},
	nav: {
		"dashboard": "Dashboard",
		"whatsapp": "WhatsApp",
		"users": "Users",
		"roles": "Roles",
		"plans": "Plans",
		"monthlyPlans": "الخطط الشهرية",
		"centers": "Centers",
		"groups": "Groups",
		"students": "Students",
		"certificates": "Certificates",
		"certificateDesign": "Certificate Design",
		"evaluations": "Evaluations",
		"homeworks": "Assignments",
		"absenceRules": "Absence Rules",
		"messageTemplates": "Message Templates",
		"activityLogs": "Activity Logs",
		"settings": "Settings",
		"management": "Management",
		"lists": "Lists",
		"studentTools": "Student Tools"
	},
	topbar: {
		"openSidebar": "Open sidebar",
		"expandSidebar": "Expand sidebar",
		"collapseSidebar": "Collapse sidebar",
		"lightMode": "Light mode",
		"darkMode": "Dark mode",
		"enterFullscreen": "Enter fullscreen",
		"exitFullscreen": "Exit fullscreen",
		"logout": "Logout",
		"admin": "Admin",
		"openProfileMenu": "Open profile menu"
	},
	common: {
		"app": "App",
		"search": "Search",
		"create": "Create",
		"cancel": "Cancel",
		"edit": "Edit",
		"delete": "Delete",
		"history": "History",
		"save": "Save",
		"saveChanges": "Save Changes",
		"close": "Close",
		"loading": "Loading...",
		"id": "ID",
		"actions": "Actions",
		"noRecords": "No records found.",
		"records": "Records",
		"selectedCount": "{0} selected",
		"na": "N/A",
		"yes": "Yes",
		"no": "No",
		"active": "Active",
		"inactive": "Inactive",
		"success": "Success",
		"error": "Error",
		"info": "Info",
		"required": "required"
	},
	breadcrumbs: {
		"ariaLabel": "Breadcrumb",
		"admin": "Admin",
		"dashboard": "Dashboard",
		"whatsapp": "WhatsApp",
		"users": "Users",
		"roles": "Roles",
		"plans": "Plans",
		"monthlyPlans": "الخطط الشهرية",
		"centers": "Centers",
		"groups": "Groups",
		"students": "Students",
		"certificates": "Certificates",
		"certificateDesign": "Certificate Design",
		"evaluations": "Evaluations",
		"homeworks": "Assignments",
		"absenceRules": "Absence Rules",
		"messageTemplates": "Message Templates",
		"activityLogs": "Activity Logs",
		"settings": "Settings",
		"password": "Password",
		"create": "Create",
		"edit": "Edit"
	},
	profile: {
		"updatePassword": "Update Password",
		"passwordDescription": "Change your account password securely.",
		"currentPassword": "Current Password",
		"newPassword": "New Password"
	},
	users: {
		"title": "Users",
		"tableTitle": "Users Table",
		"searchUsers": "Search Users",
		"createUser": "Create User",
		"editUser": "Edit User",
		"newUser": "New User",
		"addNew": "Add a new user account to the system.",
		"editDescription": "Update user profile details or set a new password.",
		"newUserDescription": "Fill all required fields to create a user.",
		"name": "Name",
		"role": "Role",
		"confirmPassword": "Confirm Password",
		"newPassword": "New Password",
		"createdAt": "Created At",
		"deleteConfirm": "Delete \"{name}\"? This action cannot be undone.",
		"deleteUser": "Delete User"
	},
	roles: {
		"title": "Roles",
		"tableTitle": "Roles Table",
		"searchRoles": "Search Roles",
		"createRole": "Create Role",
		"editRole": "Edit Role",
		"permissions": "Permissions",
		"roleName": "Role Name",
		"createdAt": "Created At",
		"permissionsCount": "Permissions",
		"createDescription": "Define a role and attach permissions for admin access control.",
		"editDescription": "Update role name and permissions mappings.",
		"saveRole": "Save Role",
		"deleteConfirm": "Delete role \"{name}\"? This action cannot be undone.",
		"deleteRole": "Delete Role",
		"adminRoleProtected": "Admin role is protected and cannot be edited or deleted."
	},
	plans: {
		"title": "Plans",
		"tableTitle": "Plans Table",
		"searchPlans": "Search Plans",
		"createPlan": "Create Plan",
		"editPlan": "Edit Plan",
		"newPlan": "New Plan",
		"planName": "Plan Name",
		"pointsCount": "Points Count",
		"pointsActions": "Plan Points",
		"exportPoints": "Export Plan Points",
		"importPoints": "Import Plan Points",
		"importFile": "XLSX File",
		"importFileRequired": "Please choose an XLSX file.",
		"importHint": "Importing replaces this plan's points. The export includes sort_order, weight, and standalone columns.",
		"importFailed": "Could not import plan points.",
		"importSuccess": "Plan points imported successfully.",
		"createdAt": "Created At",
		"createDescription": "Add a new student plan type.",
		"editDescription": "Update the selected plan details.",
		"deleteConfirm": "Delete plan \"{name}\"? This action cannot be undone.",
		"deletePlan": "Delete Plan"
	},
	monthlyPlans: {
		"title": "الخطط الشهرية",
		"center": "Center",
		"group": "Group",
		"groupOptional": "Group (optional)",
		"createPlan": "Create Plan",
		"newPlan": "New Plan",
		"createDescription": "Choose the center, month, year, start date, and end date to create a saved monthly plan. Group is optional; without a group, one plan is created for each group in the center.",
		"searchSavedPlans": "Search Saved Plans",
		"savedPlanDetails": "Saved Plan Details",
		"backToSavedPlans": "Back to Saved Plans",
		"planItems": "Plan Items",
		"generate": "Save Plan",
		"generateHint": "This will generate and save the monthly plan for students in {center} within the selected period.",
		"generated": "Monthly plan generated.",
		"alreadyExists": "This plan is already saved and will be shown.",
		"generateFailed": "Could not generate monthly plan.",
		"loadFailed": "Could not load monthly plans.",
		"centerRequired": "Choose a center before generating.",
		"groupRequired": "Choose a group before generating the monthly plan.",
		"noPlans": "No monthly plans match these filters.",
		"savedPlans": "Saved Plans",
		"savedPlansHint": "Each group can have only one plan for the same month and year.",
		"noSavedPlans": "No saved plans match these filters.",
		"viewPlan": "View",
		"openPublicReport": "Open Plan Link",
		"deletePlan": "Delete Plan",
		"deleteConfirm": "Delete {group} plan for {month} {year}?",
		"deleted": "Monthly plan deleted successfully.",
		"deleteFailed": "Could not delete monthly plan.",
		"refreshFuture": "Refresh Distribution",
		"refreshFutureTitle": "Edit plan from a selected date",
		"refreshFromDate": "From Date",
		"refreshFutureHint": "Previous days stay unchanged, the selected holiday dates are saved, and this date onward is redistributed.",
		"refreshFutureConfirm": "Refresh the plan from {date} onward?",
		"generatedAt": "Generated At",
		"month": "Month",
		"year": "Year",
		"startDate": "Start Date",
		"endDate": "End Date",
		"holidayDates": "Holiday Dates",
		"noHolidayDates": "No holiday dates selected",
		"removeHolidayDate": "Remove holiday date",
		"clearHolidayDates": "Clear holiday dates",
		"period": "Period",
		"monthlyGridHint": "Student names are on the right, and assignments are distributed across the center working days in the selected period.",
		"student": "Student",
		"searchStudent": "Search by student name",
		"searchStudentPlaceholder": "Search by student name...",
		"noStudentSearchResults": "No students match this name.",
		"studentsCount": "Students",
		"workingDaysCount": "Working Days",
		"date": "Date",
		"items": "Items",
		"itemsCount": "Items",
		"skippedItems": "Skipped Items",
		"weight": "Weight",
		"totalWeight": "Total Weight",
		"maxDailyWeight": "Daily Limit",
		"dailyWeightLimit": "Day Limit",
		"dailyWeightLimits": "Day Limits",
		"standalone": "Standalone",
		"completionPercentage": "Completion",
		"completedItems": "Completed",
		"dayCompletion": "Day Completion",
		"completedOnTime": "Done on time",
		"notCompletedOnTime": "Not done on time",
		"completedOnPlanDate": "Done on plan day",
		"completedOnDate": "Done on {date}",
		"completedBeforeDueDate": "Done early {date}",
		"notCompleted": "Not done",
		"evaluationAbsence": "Evaluation absence",
		"months": {
			"1": "January",
			"2": "February",
			"3": "March",
			"4": "April",
			"5": "May",
			"6": "June",
			"7": "July",
			"8": "August",
			"9": "September",
			"10": "October",
			"11": "November",
			"12": "December"
		}
	},
	centers: {
		"title": "Centers",
		"tableTitle": "Centers Table",
		"searchCenters": "Search Centers",
		"createCenter": "Create Center",
		"editCenter": "Edit Center",
		"newCenter": "New Center",
		"centerName": "Center Name",
		"studentType": "Student Type",
		"studentTypeHint": "Choose the student type registered at this center.",
		"maleStudents": "Male",
		"femaleStudents": "Female",
		"certificateSettings": "Certificate Settings",
		"certificateSettingsDescription": "Customize the center identity and manager signature shown on student certificates.",
		"certificateName": "Center Name on Certificate",
		"certificateNameHint": "Leave blank to use the primary center name.",
		"showCenterManagerSignature": "Show Center Manager Signature",
		"centerManagerSignatureHint": "When hidden, the center logo, manager title, stamp, and signature are removed, and the project identity moves into the center position.",
		"phone": "Phone",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneRequired": "Phone number is required.",
		"phoneErrorInvalid": "Invalid number.",
		"phoneErrorInvalidCountryCode": "Invalid country code.",
		"phoneErrorTooShort": "Number is too short.",
		"phoneErrorTooLong": "Number is too long.",
		"phoneErrorInvalidLength": "Invalid number length.",
		"whatsappGroup": "WhatsApp Group ID",
		"noWhatsappGroups": "No WhatsApp groups found. Connect WhatsApp first, then reload this page.",
		"workingDays": "Working Days",
		"createdAt": "Created At",
		"createDescription": "Add a center with its student type and phone number.",
		"editDescription": "Update center details and student type; schedules and WhatsApp are managed on groups.",
		"deleteConfirm": "Delete center \"{name}\"? This action cannot be undone.",
		"deleteCenter": "Delete Center"
	},
	groups: {
		"title": "Groups",
		"tableTitle": "Groups Table",
		"searchGroups": "Search Groups",
		"createGroup": "Create Group",
		"editGroup": "Edit Group",
		"newGroup": "New Group",
		"groupName": "Group Name",
		"center": "Center",
		"whatsappGroup": "WhatsApp Group ID",
		"noWhatsappGroups": "No WhatsApp groups found. Connect WhatsApp first, then reload this page.",
		"workingDays": "Group Working Days",
		"createdAt": "Created At",
		"openHomeworkReport": "Open Group Assignments Page",
		"openPointsRanking": "Open Student Points Ranking",
		"createDescription": "Create a group, assign it to a center, and set its WhatsApp group and working days.",
		"editDescription": "Update the group, its center, WhatsApp group, and working days.",
		"deleteConfirm": "Delete group \"{name}\"? This action cannot be undone.",
		"deleteGroup": "Delete Group"
	},
	students: {
		"title": "Students",
		"tableTitle": "Students Table",
		"searchStudents": "Search Students",
		"createStudent": "Create Student",
		"editStudent": "Edit Student",
		"newStudent": "New Student",
		"studentName": "Student Name",
		"firstName": "First Name",
		"secondName": "Second Name",
		"middleName": "Middle Name",
		"lastName": "Last Name",
		"idNumber": "ID Number",
		"parentPhone": "Parent Phone",
		"phone": "Phone",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneOneRequired": "At least one phone number is required.",
		"phoneErrorInvalid": "Invalid number.",
		"phoneErrorInvalidCountryCode": "Invalid country code.",
		"phoneErrorTooShort": "Number is too short.",
		"phoneErrorTooLong": "Number is too long.",
		"phoneErrorInvalidLength": "Invalid number length.",
		"dateOfBirth": "Date of Birth",
		"group": "Group",
		"groups": "Groups",
		"plan": "Plan",
		"currentPlanPoint": "Current Plan Point",
		"maxDailyWeight": "Default Weight Limit",
		"dailyWeightLimits": "Working Day Weight Limits",
		"pointsBalance": "Points Balance",
		"admin": "Responsible",
		"status": "Status",
		"statusActive": "Active",
		"statusInactive": "Inactive",
		"statusFrozen": "Frozen",
		"freezeStudent": "Freeze Student",
		"unfreezeStudent": "Unfreeze Student",
		"freezeFrom": "From Date",
		"freezeTo": "To Date",
		"freezeReason": "Freeze Reason",
		"freezeContactPhone": "Contact Number",
		"freezeFailed": "Could not freeze this student.",
		"frozenSuccess": "Student frozen successfully.",
		"unfreezeConfirm": "Unfreeze student \"{name}\"?",
		"unfreezeFailed": "Could not unfreeze this student.",
		"unfrozenSuccess": "Student unfrozen successfully.",
		"congratulatory": "Congratulatory Message",
		"congratulatoryReason": "Message Content",
		"sendCongratulatory": "Send Congratulatory",
		"congratulatoryFailed": "Could not send congratulatory message.",
		"congratulatorySent": "Congratulatory message sent successfully.",
		"exportStudents": "Export Students",
		"importStudents": "Import Students",
		"filterByCenter": "Filter by Center",
		"filterByGroup": "Filter by Group",
		"filterByPlan": "Filter by Plan",
		"filterByAdmin": "Filter by Responsible",
		"filterByStatus": "Filter by Status",
		"clearFilters": "Clear Filters",
		"exportNow": "Export",
		"importNow": "Import",
		"importFile": "XLSX File",
		"importFileRequired": "Please choose an XLSX file.",
		"importHint": "Use the exported XLSX headers and separate IDs in group_ids with commas, for example 2,5,9.",
		"importFailed": "Could not import students.",
		"importSuccess": "Students imported successfully.",
		"importReport": "Student Import Report",
		"importUpdated": "Updated",
		"importSkipped": "Skipped",
		"importLine": "Line",
		"importSkipReason": "Skip Reason",
		"createdAt": "Created At",
		"noGroupsForCenter": "No groups found for the selected center.",
		"createDescription": "Add a student and assign center, groups, and plan.",
		"editDescription": "Update student profile details.",
		"deleteConfirm": "Delete student \"{name}\"? This action cannot be undone.",
		"deleteStudent": "Delete Student"
	},
	certificates: {
		"title": "Certificates",
		"studentCertificates": "Student Certificates",
		"manageStudentCertificates": "Manage student certificates",
		"backToStudents": "Back to Students",
		"availableTitle": "Certificates Available to Issue",
		"availableHint": "Certificate checkpoints reached or passed by the student and not issued yet appear here.",
		"issuedTitle": "Issued Certificates",
		"issuedHint": "A permanent record of certificates issued to this student.",
		"planCheckpoint": "Plan Checkpoint",
		"achievementType": "Achievement Type",
		"achievementName": "Achievement",
		"achievement": "Achievement",
		"achievementDate": "Achievement Date",
		"number": "Certificate Number",
		"issuedAt": "Issued At",
		"issuedBy": "Issued By",
		"status": "Status",
		"issue": "Issue Certificate",
		"issueNow": "Issue Now",
		"issueSuccess": "Certificate issued successfully.",
		"issueFailed": "Could not issue the certificate.",
		"redesign": "Redesign Certificate",
		"redesignNow": "Apply Current Design and Content",
		"redesignSuccess": "The current design and content template were successfully applied to the certificate.",
		"redesignFailed": "Could not redesign the certificate.",
		"redesignConfirmTitle": "Confirm Certificate Redesign",
		"redesignConfirmMessage": "The currently effective design and content template for this center and achievement type will be applied to the certificate.",
		"redesignPreservesContent": "The certificate number, student, achievement, and dates stay unchanged; the design, content template, and center identity visibility are refreshed from the current settings.",
		"revoke": "Revoke Certificate",
		"revokeNow": "Revoke Now",
		"revokeSuccess": "The certificate was revoked and its record was retained.",
		"revokeFailed": "Could not revoke the certificate.",
		"revokeConfirmTitle": "Confirm Certificate Revocation",
		"revokeConfirmMessage": "The certificate record will remain, but its public verification page will show that it is revoked.",
		"revokeReason": "Internal Revocation Reason",
		"revokeReasonPlaceholder": "Enter a clear reason for revocation...",
		"revokeReasonPrivacy": "This internal reason is never shown on the public verification page.",
		"preview": "Preview Certificate",
		"downloadPdf": "Download PDF",
		"noAvailable": "No new certificates are available; all reached certificate checkpoints may already be issued.",
		"noProgress": "The student has not started the plan, so no certificate is available.",
		"noIssued": "No certificates have been issued to this student yet.",
		"notStarted": "Not started",
		"viewOnlyNotice": "You can view certificates, but issuing a new one requires student update permission.",
		"confirmTitle": "Confirm Certificate Issue",
		"confirmMessage": "A new certificate will be saved for {name}. The same plan checkpoint cannot be issued twice."
	},
	certificateDesign: /* @__PURE__ */ JSON.parse("{\"title\":\"Certificate Design\",\"description\":\"Customize the certificate frame, typography, and colors independently for each center and certificate type.\",\"open\":\"Certificate Design\",\"save\":\"Save Center Design\",\"saved\":\"Saved\",\"readOnly\":\"You can preview certificate designs, but changing them requires certificate settings update permission.\",\"validationError\":\"Some settings could not be saved. Review the highlighted fields and try again.\",\"contextTitle\":\"Certificate Being Edited\",\"contextHint\":\"Choose a center and certificate type. Every center keeps three independent designs, while student gender and wording come automatically from the center settings.\",\"studentGender\":\"Center Student Type\",\"previewCenter\":\"Center\",\"previewCenterHint\":\"Choose the center whose certificate designs you want to edit. Changes are saved only for this center.\",\"selectPreviewCenter\":\"Choose a center\",\"searchPreviewCenter\":\"Search center name\",\"noMatchingPreviewCenter\":\"No center matches your search.\",\"noPreviewCenters\":\"There are no centers yet. Add a center to preview and download a PDF.\",\"centerSettingsApplied\":\"This is the current save context. The certificate name, student gender, wording, and signature setting come automatically from the center.\",\"centerIdentityVisible\":\"Identity shown\",\"centerIdentityHidden\":\"Identity hidden\",\"certificateType\":\"Certificate Type\",\"previewAchievement\":\"Preview Achievement\",\"previewAchievementHint\":\"Choose a real certificate checkpoint from the plans to preview its achievement name exactly as issued.\",\"searchPreviewAchievement\":\"Search achievement, plan, or checkpoint\",\"noMatchingPreviewAchievement\":\"No achievement matches your search.\",\"noPreviewAchievements\":\"No plan checkpoint currently has certificate data for this type. Add achievement data to a plan checkpoint to preview it here.\",\"matrixTitle\":\"Certificate Type Designs\",\"matrixHint\":\"Each center has three designs: Surah, Juz, and Three Juz. An amber dot marks an unsaved change.\",\"configurationsCount\":\"{count} designs\",\"unsaved\":\"Unsaved changes\",\"themeTitle\":\"Theme and Frame\",\"editingContext\":\"Editing {center} · {type}\",\"themeCountLabel\":\"themes\",\"typographyAndColors\":\"Typography and Colors\",\"typographyAndColorsHint\":\"Choose a clear Arabic font, customize the text colors, or restore the theme palette.\",\"font\":\"Certificate Font\",\"invalidColor\":\"Enter a valid hexadecimal color such as #0F537F.\",\"restoreThemeColors\":\"Restore Theme Colors\",\"livePreview\":\"Live Preview\",\"previewHint\":\"The preview updates immediately when you change the center, certificate type, frame, font, or colors.\",\"downloadPreviewPdf\":\"Download Preview PDF\",\"previewPdfFailed\":\"Could not generate a PDF for the current preview.\",\"noTheme\":\"No theme\",\"noFont\":\"No font\",\"a4Landscape\":\"A4 landscape\",\"unsavedChanges\":\"Some changes are not saved. Select the center marked with an amber dot, then save its design.\",\"allSaved\":\"All center designs are saved.\",\"workspace\":{\"label\":\"Certificate settings sections\",\"design\":\"Appearance and Design\",\"content\":\"Certificate Content\"},\"content\":{\"title\":\"Certificate Content Templates\",\"description\":\"Edit certificate wording and assign the right template by center or achievement type.\",\"pageDescription\":\"Build polished certificate content templates, insert safe variables, and choose the right wording for each center and certificate type.\",\"contextTitle\":\"Content and Preview Context\",\"contextHint\":\"Choose the center, certificate type, and achievement to inspect and edit the effective template in the correct context.\",\"readOnly\":\"You can preview certificate content and its effective templates, but changing assignments requires certificate settings update permission.\",\"previewHint\":\"The preview updates as you edit template sections or change the center, certificate type, and achievement.\",\"effectiveTemplate\":\"Currently effective template\",\"legacyTemplate\":\"Legacy default wording\",\"systemTemplate\":\"System template\",\"protectedTemplate\":\"Protected from deletion\",\"systemCannotDelete\":\"System templates are protected and cannot be deleted.\",\"applyCurrentContext\":\"Apply to Current Center and Type\",\"templateLibrary\":\"Template Library\",\"templateLibraryHint\":\"Select a template to preview or edit it, or duplicate it before making a custom version.\",\"searchTemplates\":\"Search template name\",\"noTemplates\":\"No content templates have been created yet.\",\"noMatchingTemplates\":\"No template matches your search.\",\"newTemplate\":\"New Template\",\"createTemplate\":\"Create Template\",\"editTemplate\":\"Edit Template\",\"duplicateTemplate\":\"Duplicate\",\"copyName\":\"Copy of {name}\",\"saveTemplate\":\"Save Template\",\"deleteTemplate\":\"Delete Template\",\"templateCreated\":\"The certificate content template was created.\",\"templateUpdated\":\"The certificate content template was updated.\",\"templateDeleted\":\"The certificate content template was deleted.\",\"deleteFailed\":\"The certificate content template could not be deleted.\",\"confirmDeleteTemplate\":\"Delete “{name}”? This action cannot be undone.\",\"confirmDiscard\":\"You have unsaved changes. Discard them and continue?\",\"discardChanges\":\"Discard Changes\",\"editorHint\":\"Each section is rendered in its dedicated position in the certificate preview and PDF.\",\"templateReadOnly\":\"You can view and use this template, but editing template definitions requires content template management permission.\",\"templateName\":\"Template Name\",\"templateNamePlaceholder\":\"Example: Special Quran Center Template\",\"templateActive\":\"Template Active\",\"templateActiveHint\":\"Available to assign\",\"assignmentsCount\":\"{count} assignments\",\"availableVariables\":\"Available Variables\",\"variablesHint\":\"Place the cursor in a section, then select a variable to insert it at the cursor position.\",\"safeRenderingHint\":\"Content is rendered safely without executing HTML or embedded code.\",\"assignmentTitle\":\"Template Usage Scope\",\"assignmentHint\":\"Choose where this template is used. A center-and-type assignment has priority over broader defaults.\",\"assignmentTemplate\":\"Template to Apply\",\"assignmentScope\":\"Application Scope\",\"assignmentAchievementType\":\"Certificate Type\",\"assignmentCenter\":\"Center\",\"assignmentGender\":\"Student Type\",\"allAchievementTypes\":\"All Certificate Types\",\"saveAssignment\":\"Save Assignment\",\"updateAssignment\":\"Update Assignment\",\"removeAssignment\":\"Remove Assignment\",\"confirmRemoveAssignment\":\"Remove this assignment? The next matching template in the priority chain will be used automatically.\",\"existingAssignment\":\"This scope is currently assigned to “{name}”.\",\"assignmentSaved\":\"The certificate template assignment was saved.\",\"assignmentRemoved\":\"The certificate template assignment was removed.\",\"assignmentFailed\":\"The certificate template assignment could not be saved.\",\"assignmentRemoveFailed\":\"The certificate template assignment could not be removed.\",\"noActiveTemplates\":\"There is no active template to assign. Activate or create a template first.\",\"requestFailed\":\"Changes could not be saved. Review the fields and try again.\",\"scopes\":{\"global\":\"All Centers\",\"gender\":\"By Student Type\",\"center\":\"Specific Center\"},\"sources\":{\"center_type\":\"Center and Certificate Type\",\"center_all\":\"Center, All Types\",\"gender_type\":\"Student and Certificate Type\",\"gender_all\":\"Student Type Default\",\"global_type\":\"Global Certificate Type\",\"global_all\":\"Global Default\",\"legacy\":\"Legacy Default Wording\"},\"variables\":{\"studentName\":\"Student Name\",\"centerName\":\"Certificate Center Name\",\"achievementLabel\":\"Achievement Type\",\"achievementName\":\"Achievement Name\",\"planName\":\"Plan Name\",\"planPointName\":\"Plan Checkpoint Name\",\"hijriDate\":\"Hijri Date\",\"gregorianDate\":\"Gregorian Date\",\"certificateNumber\":\"Certificate Number\"},\"variableDescriptions\":{\"studentName\":\"The student's full name as captured when the certificate is issued.\",\"centerName\":\"The center name approved for certificate display.\",\"achievementLabel\":\"Surah, Juz, or Three Juz according to the certificate type.\",\"achievementName\":\"The Surah or Juz name stored on the plan checkpoint.\",\"planName\":\"The student's plan name at issuance.\",\"planPointName\":\"The achievement checkpoint name in the plan.\",\"hijriDate\":\"The achievement date in the Hijri calendar.\",\"gregorianDate\":\"The achievement date in the Gregorian calendar.\",\"certificateNumber\":\"The issued certificate's unique number.\"},\"sections\":{\"title\":{\"label\":\"Certificate Title\",\"hint\":\"The main heading shown at the top of the certificate.\"},\"quote_first\":{\"label\":\"First Half of the Quote\",\"hint\":\"Shown on the first side of the center ornament.\"},\"quote_second\":{\"label\":\"Second Half of the Quote\",\"hint\":\"Shown opposite the first half around the ornament.\"},\"intro\":{\"label\":\"Congratulations Introduction\",\"hint\":\"Insert the center variable so its certificate name is resolved automatically.\"},\"student_line\":{\"label\":\"Student Name Line\",\"hint\":\"Insert the student name variable and optionally surround it with ornaments such as ﴿ ﴾.\"},\"achievement_line\":{\"label\":\"Achievement Line\",\"hint\":\"Use the achievement type and name variables so one template works across certificate types.\"},\"closing\":{\"label\":\"Closing Prayer\",\"hint\":\"The closing text shown before signatures and dates.\"}},\"validation\":{\"nameRequired\":\"Enter a clear template name.\",\"sectionRequired\":\"This section is required and cannot be empty.\",\"requiredVariable\":\"This section must include the {variable} variable.\",\"plainTextOnly\":\"Use plain text and template variables only; HTML tags and Blade directives are not allowed.\",\"unknownVariables\":\"Unknown variable found: {variables}\",\"recommendedVariables\":\"The following variables are required in their sections: {variables}\"}},\"genders\":{\"male\":\"Male\",\"female\":\"Female\"},\"types\":{\"surah\":\"Surah\",\"part\":\"Juz\",\"three_parts\":\"Three Juz\"},\"themes\":{\"blue\":\"Blue and Gold\",\"emerald\":\"Emerald and Gold\",\"burgundy\":\"Burgundy and Gold\",\"navy\":\"Navy and Gold\",\"purple\":\"Purple and Gold\",\"black\":\"Black and Gold\",\"turquoise\":\"Turquoise and Gold\",\"rose\":\"Dusty Rose\",\"bronze\":\"Bronze and Gold\",\"royal\":\"Royal Blue and Gold\",\"indigo\":\"Indigo and Gold\",\"crimson\":\"Crimson and Gold\",\"coral\":\"Coral and Gold\",\"orange\":\"Orange and Gold\",\"copper\":\"Copper\",\"olive\":\"Olive and Gold\",\"forest\":\"Forest Green and Gold\",\"slate\":\"Slate Gray\",\"lavender\":\"Lavender and Gold\",\"mint\":\"Mint and Gold\"},\"fonts\":{\"classic\":\"Classic — Naskh and Amiri\",\"amiri\":\"Amiri\",\"naskh\":\"Arabic Naskh\",\"kufi\":\"Arabic Kufi\",\"sans_arabic\":\"Modern Arabic Sans\",\"naskh_kufi\":\"Naskh with Kufi headings\",\"naskh_nastaliq\":\"Naskh with Nastaliq headings\",\"sans_amiri\":\"Modern with Amiri headings\",\"sans_kufi\":\"Modern with Kufi headings\",\"sans_naskh\":\"Modern with Naskh headings\",\"kufi_amiri\":\"Kufi with Amiri headings\",\"sans_nastaliq\":\"Modern with Nastaliq headings\"},\"colors\":{\"heading\":\"Heading Color\",\"studentName\":\"Student Name Color\",\"content\":\"Body Text Color\",\"accent\":\"Accent and Ornament Color\"},\"preview\":{\"studentNames\":{\"male\":\"مُحَمَّد أَحْمَد العَبْدُ الله\",\"female\":\"مَرْيَم أَحْمَد العَبْدُ الله\"},\"centerLogo\":\"Center\",\"projectLogo\":\"Project\",\"centerManager\":\"Center Manager Signature\",\"projectManager\":\"Project Manager Signature\",\"achievementDate\":\"Achievement Date\"}}"),
	evaluations: {
		"title": "Evaluations",
		"tableTitle": "Evaluations Table",
		"searchEvaluations": "Search Evaluations",
		"createEvaluation": "Create Evaluation",
		"editEvaluation": "Edit Evaluation",
		"newEvaluation": "New Evaluation",
		"createDescription": "Select a center, group, and date, then score student evaluations.",
		"editDescription": "Update attendance and scores for this evaluation.",
		"scoreFieldMode": "Score Field",
		"center": "Center",
		"group": "Group",
		"date": "Date",
		"student": "Student",
		"attendance": "Attendance",
		"present": "Present",
		"excusedAbsence": "Excused Absence",
		"absence": "Absence",
		"exempt": "Exempt",
		"alhifz": "Memorization",
		"warud": "Daily Recital",
		"akhlaqi": "Behavior",
		"tajwid": "Tajwid",
		"note": "Note",
		"loadStudents": "Load Students",
		"studentsList": "Students List",
		"studentsHint": "You can adjust attendance and scores before saving.",
		"noStudentsLoaded": "Pick a center, group, and date, then load students.",
		"alreadyExists": "An evaluation already exists for this group and date.",
		"openExisting": "Open Existing Evaluation",
		"status": "Absence Alerts",
		"alertsPending": "Pending",
		"alertsSent": "Sent",
		"createdAt": "Created At",
		"openReport": "Open Evaluation Report",
		"sendAlerts": "Send Absence Alerts",
		"sendAlertsConfirm": "Send absence alerts for this evaluation now?",
		"sendAlertsFailed": "Could not send absence alerts.",
		"filters": {
			"toggle": "Filter",
			"toggleWithCount": "Filter ({count})",
			"center": "Center",
			"group": "Group",
			"dateFrom": "From Date",
			"dateTo": "To Date",
			"alertStatus": "Absence Alert Status",
			"apply": "Apply Filters",
			"clear": "Clear Filters"
		},
		"preview": {
			"title": "Absence Message Preview",
			"open": "View generated absence messages",
			"status": "Local preview",
			"localOnlyTitle": "Local mode:",
			"localOnlyDescription": "These messages are saved for review only and were not sent to WhatsApp.",
			"empty": "No absence messages were generated for this evaluation.",
			"loadFailed": "Could not load preview messages.",
			"recipients": "Recipients",
			"occurrence": "Occurrence",
			"centerGroup": "Evaluation group"
		},
		"messageLog": {
			"title": "Absence Message Log",
			"open": "View message log",
			"empty": "No absence messages have been recorded for this evaluation.",
			"loadFailed": "Could not load message log.",
			"evaluationDetails": "Evaluation details",
			"executionTime": "Execution time",
			"action": "Action",
			"resend": "Resend",
			"resendSuccess": "Message resent successfully.",
			"resendFailed": "Could not resend the message.",
			"reviewRequired": "This delivery result needs manual review, so resending is disabled to prevent duplicates.",
			"noContent": "No message content was recorded.",
			"statuses": {
				"sent": "Sent",
				"localPreview": "Local preview",
				"failed": "Failed",
				"notSent": "Not sent"
			},
			"actions": {
				"sendMessage": "Send message",
				"sendMessageAndFreeze": "Send message and freeze",
				"freezeStudent": "Freeze student",
				"dismissStudent": "Dismiss student"
			}
		},
		"deleteConfirm": "Delete the {group} evaluation at {center} on {date}?",
		"deleteEvaluation": "Delete Evaluation",
		"deleted": "Evaluation deleted successfully.",
		"deleteFailed": "Could not delete evaluation."
	},
	homeworks: {
		"title": "Assignments",
		"tableTitle": "Assignments Table",
		"searchHomeworks": "Search Assignments",
		"createHomework": "Create Assignment",
		"editHomework": "Edit Assignment",
		"newHomework": "New Assignment",
		"createDescription": "Select a center, group, and date, then load students and mark completed points.",
		"editDescription": "Update unawarded points and save this homework.",
		"center": "Center",
		"group": "Group",
		"date": "Date",
		"student": "Student",
		"studentsList": "Students List",
		"studentsHint": "Each student shows twenty next plan-point slots.",
		"searchStudent": "Search by student name",
		"searchStudentPlaceholder": "Search by student name...",
		"noStudentSearchResults": "No students match this name.",
		"noStudentsLoaded": "Pick a center, group, and date, then load students.",
		"loadStudents": "Load Students",
		"exportPdf": "Export PDF",
		"groupWorkingDaysHint": "Allowed days by group schedule: {days}",
		"alreadyExists": "A homework already exists for this group and date.",
		"openExisting": "Open Existing Assignment",
		"progress": "Student's latest reached point",
		"currentPosition": "Student's latest reached point",
		"notStarted": "Not started",
		"nextPoints": "Next Points",
		"noPlanPoints": "No plan points are available for this student.",
		"pointValue": "{points} points",
		"done": "Done",
		"awarded": "Awarded",
		"nextHomework": "Next time",
		"previousNextHomework": "Previously required",
		"balance": "Balance",
		"pointsAdjustment": "Balance Adjustment",
		"pointsAdjustmentHint": "Use a positive number to add points or a negative number to deduct points.",
		"balanceAfterAdjustment": "After Adjustment",
		"manualAdjustmentsTotal": "Manual adjustments total: {points}",
		"selectedPointsTotal": "Selected points total: {points}",
		"studentsCount": "Students",
		"completedPointsCount": "Completed Points",
		"createdAt": "Created At",
		"pointsHistory": "Points History",
		"historyDate": "Date",
		"planPoint": "Plan Point",
		"points": "Points",
		"balanceAfter": "Balance After",
		"noHistory": "No point history for this student.",
		"historyFailed": "Could not load points history.",
		"deleteConfirm": "Delete the {group} homework at {center} on {date}?",
		"deleteHomework": "Delete Assignment",
		"deleted": "Assignment deleted successfully.",
		"deleteFailed": "Could not delete assignment."
	},
	absenceRules: {
		"title": "Absence Rules",
		"tableTitle": "Absence Rules Table",
		"searchRules": "Search Absence Rules",
		"createRule": "Create Absence Rule",
		"editRule": "Edit Absence Rule",
		"newRule": "New Absence Rule",
		"center": "Center",
		"allCenters": "All Centers",
		"centerOptionalHint": "Leave empty to apply this rule to all centers.",
		"attendanceType": "Attendance Type",
		"attendanceAbsence": "Absence",
		"attendanceExcusedAbsence": "Excused Absence",
		"occurrenceNumber": "Monthly Occurrence Number",
		"occurrenceMonthlyHint": "Example: 3 means the student's third absence in the same month.",
		"action": "Action",
		"actionSendMessage": "Alert Only",
		"actionFreezeStudent": "Freeze Student",
		"actionDismissStudent": "Dismiss Student",
		"deductionPointsCount": "Deduction Points",
		"messageTemplate": "Message Template",
		"noTemplate": "No Template",
		"freezeReason": "Freeze Reason",
		"freezeWorkingDays": "Freeze Working Days Count",
		"sendToCenterGroup": "Also send to the evaluation group",
		"isActive": "Active",
		"status": "Status",
		"active": "Active",
		"inactive": "Inactive",
		"createdAt": "Created At",
		"createDescription": "Set attendance type, occurrence, action, and deduction points when needed.",
		"editDescription": "Update rule conditions and execution behavior.",
		"deleteConfirm": "Delete absence rule for \"{center}\" (occurrence {occurrence})?",
		"deleteRule": "Delete Rule",
		"deleted": "Absence rule deleted successfully.",
		"deleteFailed": "Could not delete absence rule."
	},
	messageTemplates: {
		"title": "Message Templates",
		"tableTitle": "Message Templates Table",
		"searchTemplates": "Search Message Templates",
		"createTemplate": "Create Message Template",
		"editTemplate": "Edit Message Template",
		"newTemplate": "New Message Template",
		"templateName": "Template Name",
		"key": "Key",
		"locale": "Locale",
		"localeArabic": "Arabic",
		"localeEnglish": "English",
		"content": "Message Content",
		"placeholdersHint": "You can use placeholders like: student.full_name, evaluation.date_ar, freeze.reason, rule.deduction_points_count",
		"isActive": "Active",
		"status": "Status",
		"active": "Active",
		"inactive": "Inactive",
		"createdAt": "Created At",
		"createDescription": "Create reusable message templates for the system.",
		"editDescription": "Update template text and placeholder usage.",
		"deleteConfirm": "Delete message template \"{name}\"?",
		"deleteTemplate": "Delete Template",
		"deleted": "Message template deleted successfully.",
		"deleteFailed": "Could not delete message template."
	},
	days: {
		"sunday": "Sunday",
		"monday": "Monday",
		"tuesday": "Tuesday",
		"wednesday": "Wednesday",
		"thursday": "Thursday",
		"friday": "Friday",
		"saturday": "Saturday"
	},
	activityLogs: {
		"title": "Activity Logs",
		"tableTitle": "Activity Logs",
		"searchLogs": "Search Logs",
		"historyFor": "History: {name}",
		"noHistory": "No activity history found for this item.",
		"noChanges": "No before/after changes captured for this event.",
		"field": "Field",
		"before": "Before",
		"after": "After",
		"by": "By",
		"description": "Description",
		"event": "Event",
		"subject": "Subject",
		"causer": "Causer",
		"createdAt": "Created At"
	},
	dashboard: {
		"title": "Dashboard",
		"eyebrow": "Live overview",
		"subtitle": "A connected view of students, attendance, assignments, centers, and WhatsApp status.",
		"empty": "No data yet.",
		"percentValue": "{value}%",
		"summaryStrip": {
			"ariaLabel": "Dashboard summary",
			"centers": "{count} centers",
			"groups": "{count} groups",
			"plans": "{count} plans",
			"whatsapp": "{connected}/{total} WhatsApp"
		},
		"metrics": {
			"students": "Students",
			"studentsSubtitle": "{active} active, {frozen} frozen",
			"attendanceRate": "Attendance rate",
			"attendanceSubtitle": "{present} present out of {total} in 30 days",
			"homeworkPoints": "Assignment points",
			"homeworkSubtitle": "{points} points awarded across {count} assignments this month",
			"evaluations": "Monthly evaluations",
			"evaluationsSubtitle": "{centers} centers and {groups} groups"
		},
		"charts": {
			"attendanceTrend": "Attendance Trend",
			"attendanceTrendSubtitle": "Last 14 days from evaluation records",
			"studentStatus": "Student Status",
			"studentStatusSubtitle": "Current student distribution by status",
			"homeworkProgress": "Assignment Completion",
			"homeworkProgressSubtitle": "Latest assignments, completed versus pending"
		},
		"statuses": {
			"active": "Active",
			"frozen": "Frozen",
			"inactive": "Inactive"
		},
		"attendance": {
			"present": "Present",
			"absent": "Absent",
			"excused": "Excused"
		},
		"homeworks": {
			"completed": "Completed",
			"pending": "Pending"
		},
		"alerts": {
			"title": "Signals",
			"subtitle": "Operational items that may need follow-up",
			"studentsWithoutPlan": {
				"title": "Students without a plan",
				"description": "{count} students need a plan assignment"
			},
			"studentsWithoutGroup": {
				"title": "Students without a group",
				"description": "{count} students need a group assignment"
			},
			"failedAbsenceMessages": {
				"title": "Failed absence messages",
				"description": "{count} messages failed in the last 30 days"
			},
			"recentEvaluations": {
				"title": "Recent evaluations",
				"description": "{count} evaluations in the last 7 days"
			},
			"whatsappDevices": {
				"title": "WhatsApp devices",
				"description": "{connected} of {total} devices connected"
			}
		},
		"centerPerformance": {
			"title": "Center Performance",
			"subtitle": "Most active centers by student count",
			"meta": "{active} active of {students} students, {groups} groups",
			"activityValue": "{evaluations} evals / {homeworks} assignments"
		},
		"recentActivity": {
			"title": "Recent Activity",
			"subtitle": "Latest evaluations, assignments, and absence alerts"
		},
		"activityTypes": {
			"evaluation": "Evaluation",
			"homework": "Assignment",
			"absence": "Absence"
		},
		"actions": {
			"title": "Quick Actions",
			"subtitle": "Shortcuts for common daily work",
			"createStudent": "Add Student",
			"createStudentMeta": "Open a new student form",
			"createEvaluation": "Add Evaluation",
			"createEvaluationMeta": "Pick center and date",
			"createHomework": "Add Assignment",
			"createHomeworkMeta": "Record student progress"
		}
	},
	whatsapp: {
		"title": "WhatsApp",
		"description": "Manage your WhatsApp session and send quick test messages.",
		"deviceFallback": "Main Device",
		"deleteDevice": "Delete Device",
		"deleteConfirm": "Delete device \"{name}\"? This will reset the current session.",
		"deviceDeleted": "Device deleted successfully.",
		"deleteFailed": "Could not delete the device.",
		"apiMissing": "WhatsApp API is not configured.",
		"apiMissingHelp": "Set WHATSAPP_API_URL (and optional WHATSAPP_API_KEY) in your environment file.",
		"instructionsTitle": "Use WhatsApp on this system",
		"step1": "Open WhatsApp on your phone.",
		"step2": "Tap Menu on Android, or Settings on iPhone.",
		"step3": "Tap Linked devices, then Link a device.",
		"step4": "Point your phone at this screen to scan the QR code.",
		"scanHint": "QR refreshes automatically every 30 seconds.",
		"refreshNow": "Refresh now",
		"connected": "Device is connected. You can send a message now.",
		"phone": "Phone",
		"message": "Message",
		"phonePlaceholder": "962799988888",
		"messagePlaceholder": "Test",
		"send": "Send",
		"sendSuccess": "Message sent successfully.",
		"sendFailed": "Could not send WhatsApp message.",
		"refreshFailed": "Could not refresh QR state."
	},
	settings: {
		"title": "Settings",
		"branding": "Branding",
		"brandingDescription": "Control app name, tagline, and branding assets used in sidebar and login.",
		"brandName": "Brand Name",
		"brandTagline": "Brand Tagline",
		"lightModeLogo": "Light Mode Logo",
		"darkModeLogo": "Dark Mode Logo",
		"appIcon": "App Icon",
		"noLogoUploaded": "No logo uploaded",
		"uploadLightLogo": "Upload Light Logo",
		"uploadDarkLogo": "Upload Dark Logo",
		"uploadIcon": "Upload Icon",
		"recommendedLogo": "Recommended: transparent logo, around 36px height.",
		"recommendedDarkLogo": "Use a light-colored logo for dark backgrounds.",
		"recommendedIcon": "Recommended: square icon at 48x48px or 64x64px.",
		"currentLightModeLogo": "Current light mode logo",
		"currentDarkModeLogo": "Current dark mode logo",
		"currentAppIcon": "Current app icon",
		"localization": "Localization",
		"localizationDescription": "Set default language and interface direction (LTR/RTL).",
		"defaultLanguage": "Default Language",
		"interfaceDirection": "Interface Direction",
		"dateTime": "Date & Time",
		"dateTimeDescription": "Set global timezone and formatting standards.",
		"dateFormat": "Date Format",
		"timeFormat": "Time Format",
		"timezone": "Timezone",
		"searchTimezone": "Search timezone...",
		"appearance": "Appearance",
		"appearanceDescription": "Customize mode, component shape, and accent color for the active theme.",
		"mode": "Mode",
		"componentShape": "Component Shape",
		"sidebarBehavior": "Sidebar Size",
		"sidebarDefault": "Default",
		"sidebarCondensed": "Condensed",
		"sidebarHidden": "Hidden",
		"sidebarSmallHoverActive": "Small Hover Active",
		"sidebarSmallHover": "Small Hover",
		"fontFamily": "Font Family",
		"accentColor": "Accent Color ({mode})",
		"light": "Light",
		"dark": "Dark",
		"compact": "Compact",
		"comfortable": "Comfortable",
		"rounded": "Rounded",
		"accent": "Accent",
		"english": "English",
		"arabic": "Arabic",
		"ltr": "LTR",
		"rtl": "RTL",
		"uploadAppIcon": "Upload App Icon",
		"uploadDarkModeLogo": "Upload Dark Mode Logo",
		"uploadLightModeLogo": "Upload Light Mode Logo"
	},
	uploads: {
		"uploadImage": "Upload Image",
		"current": "Current",
		"selected": "Selected",
		"selectedPreview": "Selected preview",
		"noImageSet": "No image set",
		"noFileSelected": "No file selected",
		"allowedFormats": "Allowed: JPG, PNG, WEBP. Max size: 2MB.",
		"upload": "Upload",
		"uploadCompleted": "Upload completed."
	},
	notifications: {
		"settingsSaved": "Your changes were saved successfully.",
		"settingsSavedTitle": "Settings Saved",
		"saveFailedTitle": "Save Failed",
		"saveFailedDetail": "Could not save settings. Please try again.",
		"loadFailedTitle": "Load Failed",
		"loadFailedDetail": "Could not load table data. Please try again.",
		"requestFailedTitle": "Request Failed",
		"requestFailedDetail": "Something went wrong. Please try again.",
		"deleteFailedTitle": "Delete Failed",
		"deleteUserFailed": "Could not delete this user.",
		"deleteRoleFailed": "Could not delete this role.",
		"deletePlanFailed": "Could not delete this plan.",
		"deleteCenterFailed": "Could not delete this center.",
		"deleteGroupFailed": "Could not delete this group.",
		"deleteStudentFailed": "Could not delete this student.",
		"userDeleted": "User deleted successfully.",
		"roleDeleted": "Role deleted successfully.",
		"planDeleted": "Plan deleted successfully.",
		"centerDeleted": "Center deleted successfully.",
		"groupDeleted": "Group deleted successfully.",
		"studentDeleted": "Student deleted successfully.",
		"imageUploaded": "Image uploaded successfully.",
		"uploadFailedTitle": "Upload Failed",
		"uploadFailedDetail": "Could not upload image. Please use JPG, PNG, or WEBP under 2MB."
	},
	errors: {
		"forbidden": {
			"title": "Access Denied",
			"description": "You do not have permission to access this page."
		},
		"notFound": {
			"title": "Page Not Found",
			"description": "The page you requested could not be found."
		},
		"expired": {
			"title": "Session Expired",
			"description": "Your session has expired. Please refresh and try again."
		},
		"serverError": {
			"title": "Server Error",
			"description": "Something went wrong on our side. Please try again in a moment."
		},
		"unavailable": {
			"title": "Service Unavailable",
			"description": "The service is temporarily unavailable. Please try again shortly."
		},
		"actions": {
			"backToDashboard": "Back to Dashboard",
			"backToHome": "Back to Home",
			"tryAgain": "Try Again"
		}
	}
};
//#endregion
//#region resources/js/i18n/index.js
var SUPPORTED_LOCALES = ["en", "ar"];
var i18nInstance = null;
var normalizeLocale = (locale) => SUPPORTED_LOCALES.includes(locale) ? locale : "ar";
var createAppI18n = (locale = "ar") => {
	i18nInstance = createI18n({
		legacy: false,
		locale: normalizeLocale(locale),
		fallbackLocale: "ar",
		messages: {
			en: en_default,
			ar: ar_default
		}
	});
	return i18nInstance;
};
var setI18nLocale = (locale) => {
	if (!i18nInstance) return;
	i18nInstance.global.locale.value = normalizeLocale(locale);
};
//#endregion
//#region resources/js/ssr.js
createServer((page) => createInertiaApp({
	page,
	render: renderToString,
	title: (title) => title ? `${title} | Vita` : "Vita",
	resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, /* #__PURE__ */ Object.assign({
		"./Pages/Admin/AbsenceRules/Create.vue": () => import("./assets/Create-BogKf8No.js"),
		"./Pages/Admin/AbsenceRules/Edit.vue": () => import("./assets/Edit-_BjiZz5X.js"),
		"./Pages/Admin/AbsenceRules.vue": () => import("./assets/AbsenceRules-CNhRiRQH.js"),
		"./Pages/Admin/ActivityLogs.vue": () => import("./assets/ActivityLogs-C2x8WJwM.js"),
		"./Pages/Admin/Centers/Create.vue": () => import("./assets/Create-DcbG56nF.js"),
		"./Pages/Admin/Centers/Edit.vue": () => import("./assets/Edit-zuJVwgQO.js"),
		"./Pages/Admin/Centers.vue": () => import("./assets/Centers-BUPYGEcx.js"),
		"./Pages/Admin/CertificateDesigns.vue": () => import("./assets/CertificateDesigns-Cjh9a9Es.js"),
		"./Pages/Admin/Dashboard.vue": () => import("./assets/Dashboard-D9clSD-v.js"),
		"./Pages/Admin/Evaluations/Create.vue": () => import("./assets/Create-3-l_16eh.js"),
		"./Pages/Admin/Evaluations/Edit.vue": () => import("./assets/Edit-aIp7sgko.js"),
		"./Pages/Admin/Evaluations.vue": () => import("./assets/Evaluations-8RcI_a82.js"),
		"./Pages/Admin/Groups/Create.vue": () => import("./assets/Create-C2qC0ZKC.js"),
		"./Pages/Admin/Groups/Edit.vue": () => import("./assets/Edit-Db5akvid.js"),
		"./Pages/Admin/Groups.vue": () => import("./assets/Groups-BYIP6JgO.js"),
		"./Pages/Admin/Homeworks/Create.vue": () => import("./assets/Create-DCK9r13N.js"),
		"./Pages/Admin/Homeworks/Edit.vue": () => import("./assets/Edit-CZ4MNrfs.js"),
		"./Pages/Admin/Homeworks.vue": () => import("./assets/Homeworks-BQE7y4Eb.js"),
		"./Pages/Admin/MessageTemplates/Create.vue": () => import("./assets/Create-DZg3SwON.js"),
		"./Pages/Admin/MessageTemplates/Edit.vue": () => import("./assets/Edit-dEuz7SAg.js"),
		"./Pages/Admin/MessageTemplates.vue": () => import("./assets/MessageTemplates-C9XMGUkT.js"),
		"./Pages/Admin/MonthlyPlans/Create.vue": () => import("./assets/Create-COC1AJ-2.js"),
		"./Pages/Admin/MonthlyPlans/Edit.vue": () => import("./assets/Edit-DGv6R4P-.js"),
		"./Pages/Admin/MonthlyPlans.vue": () => import("./assets/MonthlyPlans-GDNh7GE3.js"),
		"./Pages/Admin/Plans/Create.vue": () => import("./assets/Create-8IPCb_aZ2.js"),
		"./Pages/Admin/Plans/Edit.vue": () => import("./assets/Edit-C4FrPAM-2.js"),
		"./Pages/Admin/Plans.vue": () => import("./assets/Plans-CRt1qPAm.js"),
		"./Pages/Admin/Profile/Password.vue": () => import("./assets/Password-CdweSNCF.js"),
		"./Pages/Admin/Roles/Create.vue": () => import("./assets/Create-DHKwgL8p.js"),
		"./Pages/Admin/Roles/Edit.vue": () => import("./assets/Edit-BXGxWCm6.js"),
		"./Pages/Admin/Roles.vue": () => import("./assets/Roles-S00Da7_Y.js"),
		"./Pages/Admin/Settings.vue": () => import("./assets/Settings-B_aXWciY.js"),
		"./Pages/Admin/Students/Certificates.vue": () => import("./assets/Certificates-B0SuEgJo.js"),
		"./Pages/Admin/Students/Create.vue": () => import("./assets/Create-0BSAcjay2.js"),
		"./Pages/Admin/Students/Edit.vue": () => import("./assets/Edit-_9IOxGFu2.js"),
		"./Pages/Admin/Students.vue": () => import("./assets/Students-BkrtUUfr.js"),
		"./Pages/Admin/Users/Create.vue": () => import("./assets/Create-CPX0fqb-2.js"),
		"./Pages/Admin/Users/Edit.vue": () => import("./assets/Edit-BjzCZ09d2.js"),
		"./Pages/Admin/Users.vue": () => import("./assets/Users-Biyz-APc.js"),
		"./Pages/Admin/WhatsApp.vue": () => import("./assets/WhatsApp-C-CWRY1Z.js"),
		"./Pages/Auth/Login.vue": () => import("./assets/Login-Cw3VBSwR.js"),
		"./Pages/Error.vue": () => import("./assets/Error-DG2VQrdd.js"),
		"./Pages/Evaluations/Report.vue": () => import("./assets/Report-qXBDZNL9.js"),
		"./Pages/Groups/HomeworkReport.vue": () => import("./assets/HomeworkReport-J1bKDF4z.js"),
		"./Pages/Groups/PointsRanking.vue": () => import("./assets/PointsRanking-Bn_sMUnl.js"),
		"./Pages/MonthlyPlans/PublicReport.vue": () => import("./assets/PublicReport-D4BYYP3x.js")
	})),
	setup({ App, props, plugin }) {
		const i18n = createAppI18n(props.initialPage?.props?.systemSettings?.language ?? "en");
		return createSSRApp({ render: () => h(App, props) }).use(plugin).use(i18n).use(PrimeVue, { theme: {
			preset: Aura,
			options: { darkModeSelector: ".dark" }
		} });
	}
}));
//#endregion
export { setI18nLocale as t };
