import { createSSRApp, h } from "vue";
import { renderToString } from "vue/server-renderer";
import { createInertiaApp } from "@inertiajs/vue3";
import createServer from "@inertiajs/vue3/server";
import PrimeVue from "primevue/config";
import Aura from "@primeuix/themes/aura";
import { createI18n } from "vue-i18n";
//#region node_modules/laravel-vite-plugin/inertia-helpers/index.js
async function resolvePageComponent(path, pages) {
	for (const p of Array.isArray(path) ? path : [path]) {
		const page = pages[p];
		if (typeof page === "undefined") continue;
		return typeof page === "function" ? page() : page;
	}
	throw new Error(`Page not found: ${path}`);
}
var ar_default = {
	auth: {
		"login": "تسجيل الدخول",
		"signIn": "تسجيل الدخول",
		"useAdminAccount": "استخدم حساب المشرف للوصول إلى لوحة التحكم.",
		"email": "البريد الإلكتروني",
		"password": "كلمة المرور",
		"rememberMe": "تذكرني",
		"appLogoAlt": "شعار {appName}"
	},
	nav: {
		"dashboard": "لوحة التحكم",
		"whatsapp": "واتساب",
		"users": "المستخدمون",
		"roles": "الأدوار",
		"plans": "الخطط",
		"centers": "المراكز",
		"groups": "المجموعات",
		"students": "الطلاب",
		"evaluations": "التقييمات",
		"homeworks": "الواجبات",
		"absenceRules": "قواعد الغياب",
		"messageTemplates": "قوالب الرسائل",
		"activityLogs": "سجل النشاط",
		"settings": "الإعدادات",
		"management": "الإدارة",
		"lists": "القوائم",
		"studentTools": "ادوات الطلاب"
	},
	topbar: {
		"openSidebar": "فتح الشريط الجانبي",
		"expandSidebar": "توسيع الشريط الجانبي",
		"collapseSidebar": "طي الشريط الجانبي",
		"lightMode": "الوضع الفاتح",
		"darkMode": "الوضع الداكن",
		"enterFullscreen": "الدخول إلى ملء الشاشة",
		"exitFullscreen": "الخروج من ملء الشاشة",
		"logout": "تسجيل الخروج",
		"admin": "المشرف",
		"openProfileMenu": "فتح قائمة الملف الشخصي"
	},
	common: {
		"app": "تطبيق",
		"search": "بحث",
		"create": "إنشاء",
		"cancel": "إلغاء",
		"edit": "تعديل",
		"delete": "حذف",
		"history": "السجل",
		"save": "حفظ",
		"saveChanges": "حفظ التغييرات",
		"close": "إغلاق",
		"loading": "جاري التحميل...",
		"id": "المعرف",
		"records": "السجلات",
		"actions": "الإجراءات",
		"noRecords": "لا توجد بيانات.",
		"selectedCount": "{0} محدد",
		"na": "غير متوفر",
		"success": "نجاح",
		"error": "خطأ",
		"info": "معلومة",
		"required": "مطلوب"
	},
	breadcrumbs: {
		"ariaLabel": "مسار التنقل",
		"admin": "الإدارة",
		"dashboard": "لوحة التحكم",
		"whatsapp": "واتساب",
		"users": "المستخدمون",
		"roles": "الأدوار",
		"plans": "الخطط",
		"centers": "المراكز",
		"groups": "المجموعات",
		"students": "الطلاب",
		"evaluations": "التقييمات",
		"homeworks": "الواجبات",
		"absenceRules": "قواعد الغياب",
		"messageTemplates": "قوالب الرسائل",
		"activityLogs": "سجل النشاط",
		"settings": "الإعدادات",
		"password": "كلمة المرور",
		"create": "إنشاء",
		"edit": "تعديل"
	},
	profile: {
		"updatePassword": "تحديث كلمة المرور",
		"passwordDescription": "غيّر كلمة مرور حسابك بشكل آمن.",
		"currentPassword": "كلمة المرور الحالية",
		"newPassword": "كلمة المرور الجديدة"
	},
	users: {
		"title": "المستخدمون",
		"tableTitle": "جدول المستخدمين",
		"searchUsers": "بحث المستخدمين",
		"createUser": "إنشاء مستخدم",
		"editUser": "تعديل مستخدم",
		"newUser": "مستخدم جديد",
		"addNew": "أضف حساب مستخدم جديد إلى النظام.",
		"editDescription": "حدّث بيانات المستخدم أو عيّن كلمة مرور جديدة.",
		"newUserDescription": "املأ جميع الحقول المطلوبة لإنشاء مستخدم.",
		"name": "الاسم",
		"role": "الدور",
		"confirmPassword": "تأكيد كلمة المرور",
		"newPassword": "كلمة المرور الجديدة",
		"createdAt": "تاريخ الإنشاء",
		"deleteConfirm": "حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteUser": "حذف المستخدم"
	},
	roles: {
		"title": "الأدوار",
		"tableTitle": "جدول الأدوار",
		"searchRoles": "بحث الأدوار",
		"createRole": "إنشاء دور",
		"editRole": "تعديل دور",
		"permissions": "الصلاحيات",
		"roleName": "اسم الدور",
		"createdAt": "تاريخ الإنشاء",
		"permissionsCount": "الصلاحيات",
		"createDescription": "عرّف دورًا واربطه بالصلاحيات للتحكم في الوصول.",
		"editDescription": "حدّث اسم الدور وربط الصلاحيات.",
		"saveRole": "حفظ الدور",
		"deleteConfirm": "حذف الدور \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteRole": "حذف الدور",
		"adminRoleProtected": "دور المشرف محمي ولا يمكن تعديله أو حذفه."
	},
	plans: {
		"title": "الخطط",
		"tableTitle": "جدول الخطط",
		"searchPlans": "بحث الخطط",
		"createPlan": "إنشاء خطة",
		"editPlan": "تعديل خطة",
		"newPlan": "خطة جديدة",
		"planName": "اسم الخطة",
		"pointsCount": "عدد النقاط",
		"pointsActions": "نقاط الخطة",
		"exportPoints": "استخراج نقاط الخطة",
		"importPoints": "إدخال نقاط الخطة",
		"importFile": "ملف XLSX",
		"importFileRequired": "يرجى اختيار ملف XLSX.",
		"importHint": "استيراد الملف يستبدل نقاط هذه الخطة بالأعمدة: خطة التسميع، النقاط، أخذ الشهادة، اسم السورة، اسم الجزء، رقم الثلاث أجزاء.",
		"importFailed": "تعذر إدخال نقاط الخطة.",
		"importSuccess": "تم إدخال نقاط الخطة بنجاح.",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أضف نوع خطة جديد للطلاب.",
		"editDescription": "حدّث تفاصيل الخطة المحددة.",
		"deleteConfirm": "حذف الخطة \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deletePlan": "حذف الخطة"
	},
	centers: {
		"title": "المراكز",
		"tableTitle": "جدول المراكز",
		"searchCenters": "بحث المراكز",
		"createCenter": "إنشاء مركز",
		"editCenter": "تعديل مركز",
		"newCenter": "مركز جديد",
		"centerName": "اسم المركز",
		"phone": "الهاتف",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneRequired": "رقم الهاتف مطلوب.",
		"phoneErrorInvalid": "رقم غير صالح.",
		"phoneErrorInvalidCountryCode": "مفتاح الدولة غير صالح.",
		"phoneErrorTooShort": "الرقم قصير جدًا.",
		"phoneErrorTooLong": "الرقم طويل جدًا.",
		"phoneErrorInvalidLength": "طول الرقم غير صالح.",
		"whatsappGroup": "معرّف مجموعة واتساب",
		"noWhatsappGroups": "لم يتم العثور على مجموعات واتساب. اربط واتساب أولاً ثم أعد تحميل الصفحة.",
		"workingDays": "أيام الدوام",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أضف مركزًا مع الهاتف وأيام الدوام.",
		"editDescription": "حدّث بيانات المركز وجدوله.",
		"deleteConfirm": "حذف المركز \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteCenter": "حذف المركز"
	},
	groups: {
		"title": "المجموعات",
		"tableTitle": "جدول المجموعات",
		"searchGroups": "بحث المجموعات",
		"createGroup": "إنشاء مجموعة",
		"editGroup": "تعديل مجموعة",
		"newGroup": "مجموعة جديدة",
		"groupName": "اسم المجموعة",
		"center": "المركز",
		"createdAt": "تاريخ الإنشاء",
		"openHomeworkReport": "فتح صفحة واجبات المجموعة",
		"createDescription": "أنشئ مجموعة وربطها بمركز.",
		"editDescription": "حدّث اسم المجموعة أو غيّر المركز.",
		"deleteConfirm": "حذف المجموعة \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteGroup": "حذف المجموعة"
	},
	students: {
		"title": "الطلاب",
		"tableTitle": "جدول الطلاب",
		"searchStudents": "بحث الطلاب",
		"createStudent": "إنشاء طالب",
		"editStudent": "تعديل طالب",
		"newStudent": "طالب جديد",
		"studentName": "اسم الطالب",
		"firstName": "الاسم الأول",
		"secondName": "اسم الأب",
		"middleName": "اسم الجد",
		"lastName": "اسم العائلة",
		"idNumber": "الرقم الوطني",
		"parentPhone": "هاتف ولي الأمر",
		"phone": "الهاتف",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneOneRequired": "يجب إدخال رقم هاتف واحد على الأقل.",
		"phoneErrorInvalid": "رقم غير صالح.",
		"phoneErrorInvalidCountryCode": "مفتاح الدولة غير صالح.",
		"phoneErrorTooShort": "الرقم قصير جدًا.",
		"phoneErrorTooLong": "الرقم طويل جدًا.",
		"phoneErrorInvalidLength": "طول الرقم غير صالح.",
		"dateOfBirth": "تاريخ الميلاد",
		"group": "المجموعة",
		"plan": "الخطة",
		"admin": "المسؤول",
		"status": "الحالة",
		"statusActive": "فعال",
		"statusInactive": "غير فعال",
		"statusFrozen": "مجمّد",
		"freezeStudent": "تجميد الطالب",
		"unfreezeStudent": "فك تجميد الطالب",
		"freezeFrom": "من تاريخ",
		"freezeTo": "إلى تاريخ",
		"freezeReason": "سبب التجميد",
		"freezeContactPhone": "رقم التواصل",
		"freezeFailed": "تعذر تجميد هذا الطالب.",
		"frozenSuccess": "تم تجميد الطالب بنجاح.",
		"unfreezeConfirm": "فك تجميد الطالب \"{name}\"؟",
		"unfreezeFailed": "تعذر فك تجميد هذا الطالب.",
		"unfrozenSuccess": "تم فك تجميد الطالب بنجاح.",
		"congratulatory": "رسالة تهنئة",
		"congratulatoryReason": "نص الرسالة",
		"sendCongratulatory": "إرسال التهنئة",
		"congratulatoryFailed": "تعذر إرسال رسالة التهنئة.",
		"congratulatorySent": "تم إرسال رسالة التهنئة بنجاح.",
		"exportStudents": "استخراج الطلاب",
		"importStudents": "ادخال الطلاب",
		"filterByCenter": "تصفية حسب المركز",
		"exportNow": "استخراج",
		"importNow": "ادخال",
		"importFile": "ملف XLSX",
		"importFileRequired": "يرجى اختيار ملف XLSX.",
		"importHint": "استخدم ملف XLSX بنفس أعمدة ملف الاستخراج.",
		"importFailed": "تعذر ادخال الطلاب.",
		"importSuccess": "تم ادخال الطلاب بنجاح.",
		"createdAt": "تاريخ الإنشاء",
		"noGroupsForCenter": "لا توجد مجموعات للمركز المختار.",
		"createDescription": "أضف طالبًا واربطه بالمركز والمجموعة والخطة.",
		"editDescription": "حدّث بيانات الطالب.",
		"deleteConfirm": "حذف الطالب \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
		"deleteStudent": "حذف الطالب"
	},
	evaluations: {
		"title": "التقييمات",
		"tableTitle": "جدول التقييمات",
		"searchEvaluations": "بحث التقييمات",
		"createEvaluation": "إضافة تقييم",
		"editEvaluation": "تعديل تقييم",
		"newEvaluation": "تقييم جديد",
		"createDescription": "اختر المركز والتاريخ ثم أدخل تقييمات الطلاب.",
		"editDescription": "عدّل درجات وحضور الطلاب لهذا التقييم.",
		"scoreFieldMode": "حقل التقييم",
		"center": "المركز",
		"date": "التاريخ",
		"student": "الطالب",
		"attendance": "الحضور",
		"present": "حاضر",
		"excusedAbsence": "غائب بعذر",
		"absence": "غائب بدون عذر",
		"exempt": "معفى",
		"alhifz": "الحفظ",
		"warud": "الورد",
		"akhlaqi": "الأخلاق",
		"tajwid": "التجويد",
		"note": "ملاحظة",
		"loadStudents": "تحميل الطلاب",
		"studentsList": "قائمة الطلاب",
		"studentsHint": "يمكن تعديل حالة الحضور ودرجات كل طالب قبل الحفظ.",
		"noStudentsLoaded": "اختر مركزًا وتاريخًا ثم حمّل الطلاب.",
		"alreadyExists": "يوجد تقييم مسجل لهذا المركز في نفس التاريخ.",
		"openExisting": "فتح التقييم الحالي",
		"status": "تنبيهات الغياب",
		"alertsPending": "غير مرسلة",
		"alertsSent": "مرسلة",
		"createdAt": "تاريخ الإنشاء",
		"openReport": "فتح تقرير التقييم",
		"sendAlerts": "إرسال تنبيهات الغياب",
		"sendAlertsConfirm": "إرسال تنبيهات الغياب لهذا التقييم الآن؟",
		"sendAlertsFailed": "تعذر إرسال تنبيهات الغياب.",
		"deleteConfirm": "حذف تقييم {center} بتاريخ {date}؟",
		"deleteEvaluation": "حذف التقييم",
		"deleted": "تم حذف التقييم بنجاح.",
		"deleteFailed": "تعذر حذف التقييم."
	},
	homeworks: {
		"title": "الواجبات",
		"tableTitle": "جدول الواجبات",
		"searchHomeworks": "بحث الواجبات",
		"createHomework": "إضافة واجب",
		"editHomework": "تعديل واجب",
		"newHomework": "واجب جديد",
		"createDescription": "اختر المركز والتاريخ ثم حمّل الطلاب وحدد النقاط المكتملة.",
		"editDescription": "عدّل النقاط غير المحتسبة واحفظ الواجب.",
		"center": "المركز",
		"date": "التاريخ",
		"student": "الطالب",
		"studentsList": "قائمة الطلاب",
		"studentsHint": "لكل طالب تظهر عشرون خانة من نقاط الخطة التالية له.",
		"noStudentsLoaded": "اختر مركزًا وتاريخًا ثم حمّل الطلاب.",
		"loadStudents": "تحميل الطلاب",
		"alreadyExists": "يوجد واجب مسجل لهذا المركز في نفس التاريخ.",
		"openExisting": "فتح الواجب الحالي",
		"progress": "آخر نقطة وصل لها الطالب",
		"currentPosition": "آخر نقطة وصل لها الطالب",
		"notStarted": "لم يبدأ بعد",
		"nextPoints": "النقاط التالية",
		"noPlanPoints": "لا توجد نقاط متاحة لهذا الطالب.",
		"pointValue": "{points} نقطة",
		"done": "تم",
		"awarded": "محتسبة",
		"balance": "الرصيد",
		"pointsAdjustment": "تعديل الرصيد",
		"pointsAdjustmentHint": "اكتب رقمًا موجبًا للزيادة أو سالبًا للنقصان.",
		"balanceAfterAdjustment": "بعد التعديل",
		"manualAdjustmentsTotal": "إجمالي التعديلات اليدوية: {points}",
		"selectedPointsTotal": "إجمالي النقاط المحددة: {points}",
		"studentsCount": "عدد الطلاب",
		"completedPointsCount": "النقاط المكتملة",
		"createdAt": "تاريخ الإنشاء",
		"pointsHistory": "سجل النقاط",
		"historyDate": "التاريخ",
		"planPoint": "نقطة الخطة",
		"points": "النقاط",
		"balanceAfter": "الرصيد بعد",
		"noHistory": "لا يوجد سجل نقاط لهذا الطالب.",
		"historyFailed": "تعذر تحميل سجل النقاط.",
		"deleteConfirm": "حذف واجب {center} بتاريخ {date}؟",
		"deleteHomework": "حذف الواجب",
		"deleted": "تم حذف الواجب بنجاح.",
		"deleteFailed": "تعذر حذف الواجب."
	},
	absenceRules: {
		"title": "قواعد الغياب",
		"tableTitle": "جدول قواعد الغياب",
		"searchRules": "بحث قواعد الغياب",
		"createRule": "إنشاء قاعدة غياب",
		"editRule": "تعديل قاعدة غياب",
		"newRule": "قاعدة غياب جديدة",
		"center": "المركز",
		"allCenters": "كل المراكز",
		"centerOptionalHint": "اتركه فارغًا لتطبيق القاعدة على كل المراكز.",
		"attendanceType": "نوع الغياب",
		"attendanceAbsence": "غياب بدون عذر",
		"attendanceExcusedAbsence": "غياب بعذر",
		"occurrenceNumber": "رقم التكرار",
		"action": "الإجراء",
		"actionFreezeStudent": "تجميد الطالب",
		"actionDismissStudent": "فصل الطالب",
		"deductionPointsCount": "عدد نقاط الخصم",
		"messageTemplate": "قالب الرسالة",
		"noTemplate": "بدون قالب",
		"freezeReason": "سبب التجميد",
		"freezeWorkingDays": "عدد أيام الدوام للتجميد",
		"sendToCenterGroup": "الإرسال أيضًا لمجموعة المركز",
		"isActive": "فعّال",
		"status": "الحالة",
		"active": "فعال",
		"inactive": "غير فعال",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "حدّد نوع الغياب والتكرار ثم اختر الإجراء وحدد نقاط الخصم.",
		"editDescription": "حدّث شروط القاعدة أو الإجراء المرتبط بها.",
		"deleteConfirm": "حذف قاعدة الغياب لـ \"{center}\" (تكرار {occurrence})؟",
		"deleteRule": "حذف القاعدة",
		"deleted": "تم حذف قاعدة الغياب بنجاح.",
		"deleteFailed": "تعذر حذف قاعدة الغياب."
	},
	messageTemplates: {
		"title": "قوالب الرسائل",
		"tableTitle": "جدول قوالب الرسائل",
		"searchTemplates": "بحث قوالب الرسائل",
		"createTemplate": "إنشاء قالب رسالة",
		"editTemplate": "تعديل قالب رسالة",
		"newTemplate": "قالب رسالة جديد",
		"templateName": "اسم القالب",
		"key": "المفتاح",
		"locale": "اللغة",
		"localeArabic": "العربية",
		"localeEnglish": "الإنجليزية",
		"content": "محتوى الرسالة",
		"placeholdersHint": "يمكن استخدام متغيّرات مثل: student.full_name و evaluation.date_ar و freeze.reason و rule.deduction_points_count",
		"isActive": "فعّال",
		"status": "الحالة",
		"active": "فعال",
		"inactive": "غير فعال",
		"createdAt": "تاريخ الإنشاء",
		"createDescription": "أنشئ قالبًا عامًا باسم ومفتاح واضح لاستخدامه في النظام.",
		"editDescription": "حدّث نص القالب والمتغيّرات المستخدمة.",
		"deleteConfirm": "حذف قالب الرسالة \"{name}\"؟",
		"deleteTemplate": "حذف القالب",
		"deleted": "تم حذف قالب الرسالة بنجاح.",
		"deleteFailed": "تعذر حذف قالب الرسالة."
	},
	days: {
		"sunday": "الأحد",
		"monday": "الاثنين",
		"tuesday": "الثلاثاء",
		"wednesday": "الأربعاء",
		"thursday": "الخميس",
		"friday": "الجمعة",
		"saturday": "السبت"
	},
	activityLogs: {
		"title": "سجل النشاط",
		"tableTitle": "سجل النشاط",
		"searchLogs": "بحث في السجل",
		"historyFor": "سجل: {name}",
		"noHistory": "لا يوجد سجل نشاط لهذا العنصر.",
		"noChanges": "لا توجد تغييرات قبل/بعد لهذا الحدث.",
		"field": "الحقل",
		"before": "قبل",
		"after": "بعد",
		"by": "بواسطة",
		"description": "الوصف",
		"event": "الحدث",
		"subject": "العنصر",
		"causer": "المنفّذ",
		"createdAt": "تاريخ الإنشاء"
	},
	dashboard: {
		"title": "لوحة التحكم",
		"eyebrow": "نظرة مباشرة",
		"subtitle": "متابعة مترابطة للطلاب، الحضور، الواجبات، المراكز، وحالة واتساب.",
		"empty": "لا توجد بيانات بعد.",
		"percentValue": "{value}٪",
		"summaryStrip": {
			"ariaLabel": "ملخص لوحة التحكم",
			"centers": "{count} مركز",
			"groups": "{count} مجموعة",
			"plans": "{count} خطة",
			"whatsapp": "{connected}/{total} واتساب"
		},
		"metrics": {
			"students": "الطلاب",
			"studentsSubtitle": "{active} فعال، {frozen} مجمّد",
			"attendanceRate": "نسبة الحضور",
			"attendanceSubtitle": "{present} حضور من أصل {total} خلال 30 يوم",
			"homeworkPoints": "نقاط الواجبات",
			"homeworkSubtitle": "{points} نقطة ممنوحة عبر {count} واجب هذا الشهر",
			"evaluations": "تقييمات الشهر",
			"evaluationsSubtitle": "{centers} مركز و {groups} مجموعة"
		},
		"charts": {
			"attendanceTrend": "اتجاه الحضور",
			"attendanceTrendSubtitle": "آخر 14 يوم حسب سجلات التقييم",
			"studentStatus": "حالة الطلاب",
			"studentStatusSubtitle": "توزيع الطلاب حسب الحالة الحالية",
			"homeworkProgress": "إنجاز الواجبات",
			"homeworkProgressSubtitle": "آخر واجبات مسجلة، منجز مقابل متبقّي"
		},
		"statuses": {
			"active": "فعال",
			"frozen": "مجمّد",
			"inactive": "غير فعال"
		},
		"attendance": {
			"present": "حضور",
			"absent": "غياب",
			"excused": "غياب بعذر"
		},
		"homeworks": {
			"completed": "منجز",
			"pending": "متبقّي"
		},
		"alerts": {
			"title": "المؤشرات",
			"subtitle": "نقاط تحتاج متابعة تشغيلية",
			"studentsWithoutPlan": {
				"title": "طلاب بدون خطة",
				"description": "{count} طالب يحتاج ربط خطة"
			},
			"studentsWithoutGroup": {
				"title": "طلاب بدون مجموعة",
				"description": "{count} طالب يحتاج ربط مجموعة"
			},
			"failedAbsenceMessages": {
				"title": "رسائل غياب فاشلة",
				"description": "{count} رسالة لم ترسل خلال 30 يوم"
			},
			"recentEvaluations": {
				"title": "تقييمات حديثة",
				"description": "{count} تقييم خلال آخر 7 أيام"
			},
			"whatsappDevices": {
				"title": "أجهزة واتساب",
				"description": "{connected} من {total} أجهزة متصلة"
			}
		},
		"centerPerformance": {
			"title": "أداء المراكز",
			"subtitle": "أكثر المراكز نشاطاً حسب عدد الطلاب",
			"meta": "{active} فعال من {students} طالب، {groups} مجموعة",
			"activityValue": "{evaluations} تقييم / {homeworks} واجب"
		},
		"recentActivity": {
			"title": "آخر النشاط",
			"subtitle": "أحدث التقييمات والواجبات وتنبيهات الغياب"
		},
		"activityTypes": {
			"evaluation": "تقييم",
			"homework": "واجب",
			"absence": "غياب"
		},
		"actions": {
			"title": "إجراءات سريعة",
			"subtitle": "اختصارات لأكثر العمليات اليومية",
			"createStudent": "إضافة طالب",
			"createStudentMeta": "فتح نموذج طالب جديد",
			"createEvaluation": "إضافة تقييم",
			"createEvaluationMeta": "اختيار مركز وتاريخ",
			"createHomework": "إضافة واجب",
			"createHomeworkMeta": "تسجيل تقدم الطلاب"
		}
	},
	whatsapp: {
		"title": "واتساب",
		"description": "إدارة جلسة واتساب وإرسال رسائل اختبار بسرعة.",
		"deviceFallback": "الجهاز الرئيسي",
		"deleteDevice": "حذف الجهاز",
		"deleteConfirm": "حذف الجهاز \"{name}\"؟ هذا سيعيد تعيين الجلسة الحالية.",
		"deviceDeleted": "تم حذف الجهاز بنجاح.",
		"deleteFailed": "تعذر حذف الجهاز.",
		"apiMissing": "واجهة WhatsApp API غير مهيأة.",
		"apiMissingHelp": "أضف WHATSAPP_API_URL (واختياريًا WHATSAPP_API_KEY) في ملف البيئة.",
		"instructionsTitle": "استخدم واتساب على هذا النظام",
		"step1": "افتح واتساب على هاتفك.",
		"step2": "اضغط القائمة في أندرويد أو الإعدادات في iPhone.",
		"step3": "اختر الأجهزة المرتبطة ثم ربط جهاز.",
		"step4": "وجّه هاتفك إلى هذه الشاشة لمسح رمز QR.",
		"scanHint": "يتم تحديث رمز QR تلقائيًا كل 30 ثانية.",
		"refreshNow": "تحديث الآن",
		"connected": "الجهاز متصل. يمكنك إرسال رسالة الآن.",
		"phone": "الهاتف",
		"message": "الرسالة",
		"phonePlaceholder": "962799988888",
		"messagePlaceholder": "تجربة",
		"send": "إرسال",
		"sendSuccess": "تم إرسال الرسالة بنجاح.",
		"sendFailed": "تعذر إرسال رسالة واتساب.",
		"refreshFailed": "تعذر تحديث حالة QR."
	},
	settings: {
		"title": "الإعدادات",
		"branding": "الهوية البصرية",
		"brandingDescription": "تحكم باسم التطبيق والوصف وملفات الهوية المستخدمة في الشريط الجانبي وصفحة الدخول.",
		"brandName": "اسم العلامة",
		"brandTagline": "الوصف المختصر",
		"lightModeLogo": "شعار الوضع الفاتح",
		"darkModeLogo": "شعار الوضع الداكن",
		"appIcon": "أيقونة التطبيق",
		"noLogoUploaded": "لا يوجد شعار مرفوع",
		"uploadLightLogo": "رفع شعار الوضع الفاتح",
		"uploadDarkLogo": "رفع شعار الوضع الداكن",
		"uploadIcon": "رفع الأيقونة",
		"recommendedLogo": "مقترح: شعار بخلفية شفافة بارتفاع يقارب 36px.",
		"recommendedDarkLogo": "استخدم شعارًا فاتح اللون لخلفيات الوضع الداكن.",
		"recommendedIcon": "مقترح: أيقونة مربعة بحجم 48x48 أو 64x64.",
		"currentLightModeLogo": "الشعار الحالي للوضع الفاتح",
		"currentDarkModeLogo": "الشعار الحالي للوضع الداكن",
		"currentAppIcon": "أيقونة التطبيق الحالية",
		"localization": "الترجمة والاتجاه",
		"localizationDescription": "حدّد اللغة الافتراضية واتجاه الواجهة (LTR/RTL).",
		"defaultLanguage": "اللغة الافتراضية",
		"interfaceDirection": "اتجاه الواجهة",
		"dateTime": "التاريخ والوقت",
		"dateTimeDescription": "حدّد المنطقة الزمنية ومعايير التنسيق العامة.",
		"dateFormat": "تنسيق التاريخ",
		"timeFormat": "تنسيق الوقت",
		"timezone": "المنطقة الزمنية",
		"searchTimezone": "ابحث عن المنطقة الزمنية...",
		"appearance": "المظهر",
		"appearanceDescription": "خصّص الوضع وشكل المكونات ولون التمييز للوضع الحالي.",
		"mode": "الوضع",
		"componentShape": "شكل المكونات",
		"sidebarBehavior": "حجم الشريط الجانبي",
		"sidebarDefault": "افتراضي",
		"sidebarCondensed": "مكثف",
		"sidebarHidden": "مخفي",
		"sidebarSmallHoverActive": "صغير مع التوسعة عند المرور (نشط)",
		"sidebarSmallHover": "صغير مع التوسعة عند المرور",
		"fontFamily": "نوع الخط",
		"accentColor": "لون التمييز ({mode})",
		"light": "فاتح",
		"dark": "داكن",
		"compact": "مضغوط",
		"comfortable": "مريح",
		"rounded": "مستدير",
		"accent": "التمييز",
		"english": "الإنجليزية",
		"arabic": "العربية",
		"ltr": "LTR",
		"rtl": "RTL",
		"uploadAppIcon": "رفع أيقونة التطبيق",
		"uploadDarkModeLogo": "رفع شعار الوضع الداكن",
		"uploadLightModeLogo": "رفع شعار الوضع الفاتح"
	},
	uploads: {
		"uploadImage": "رفع صورة",
		"current": "الحالي",
		"selected": "المحدد",
		"selectedPreview": "معاينة الملف المحدد",
		"noImageSet": "لا توجد صورة",
		"noFileSelected": "لم يتم اختيار ملف",
		"allowedFormats": "المسموح: JPG, PNG, WEBP. الحد الأقصى: 2MB.",
		"upload": "رفع",
		"uploadCompleted": "اكتمل الرفع."
	},
	notifications: {
		"settingsSaved": "تم حفظ التغييرات بنجاح.",
		"settingsSavedTitle": "تم حفظ الإعدادات",
		"saveFailedTitle": "فشل الحفظ",
		"saveFailedDetail": "تعذر حفظ الإعدادات. حاول مرة أخرى.",
		"loadFailedTitle": "فشل التحميل",
		"loadFailedDetail": "تعذر تحميل بيانات الجدول. حاول مرة أخرى.",
		"requestFailedTitle": "فشل الطلب",
		"requestFailedDetail": "حدث خطأ ما. حاول مرة أخرى.",
		"deleteFailedTitle": "فشل الحذف",
		"deleteUserFailed": "تعذر حذف هذا المستخدم.",
		"deleteRoleFailed": "تعذر حذف هذا الدور.",
		"deletePlanFailed": "تعذر حذف هذه الخطة.",
		"deleteCenterFailed": "تعذر حذف هذا المركز.",
		"deleteGroupFailed": "تعذر حذف هذه المجموعة.",
		"deleteStudentFailed": "تعذر حذف هذا الطالب.",
		"userDeleted": "تم حذف المستخدم بنجاح.",
		"roleDeleted": "تم حذف الدور بنجاح.",
		"planDeleted": "تم حذف الخطة بنجاح.",
		"centerDeleted": "تم حذف المركز بنجاح.",
		"groupDeleted": "تم حذف المجموعة بنجاح.",
		"studentDeleted": "تم حذف الطالب بنجاح.",
		"imageUploaded": "تم رفع الصورة بنجاح.",
		"uploadFailedTitle": "فشل الرفع",
		"uploadFailedDetail": "تعذر رفع الصورة. استخدم JPG أو PNG أو WEBP بحجم أقل من 2MB."
	},
	errors: {
		"forbidden": {
			"title": "تم رفض الوصول",
			"description": "لا تملك الصلاحية للوصول إلى هذه الصفحة."
		},
		"notFound": {
			"title": "الصفحة غير موجودة",
			"description": "الصفحة المطلوبة غير موجودة."
		},
		"expired": {
			"title": "انتهت الجلسة",
			"description": "انتهت صلاحية الجلسة. حدّث الصفحة وحاول مرة أخرى."
		},
		"serverError": {
			"title": "خطأ في الخادم",
			"description": "حدث خطأ من جهة الخادم. حاول مرة أخرى بعد قليل."
		},
		"unavailable": {
			"title": "الخدمة غير متاحة",
			"description": "الخدمة غير متاحة مؤقتًا. حاول مرة أخرى بعد قليل."
		},
		"actions": {
			"backToDashboard": "العودة إلى لوحة التحكم",
			"backToHome": "العودة إلى الصفحة الرئيسية",
			"tryAgain": "إعادة المحاولة"
		}
	}
};
var en_default = {
	auth: {
		"login": "Login",
		"signIn": "Sign in",
		"useAdminAccount": "Use your admin account to access the dashboard.",
		"email": "Email",
		"password": "Password",
		"rememberMe": "Remember me",
		"appLogoAlt": "{appName} logo"
	},
	nav: {
		"dashboard": "Dashboard",
		"whatsapp": "WhatsApp",
		"users": "Users",
		"roles": "Roles",
		"plans": "Plans",
		"centers": "Centers",
		"groups": "Groups",
		"students": "Students",
		"evaluations": "Evaluations",
		"homeworks": "Assignments",
		"absenceRules": "Absence Rules",
		"messageTemplates": "Message Templates",
		"activityLogs": "Activity Logs",
		"settings": "Settings",
		"management": "Management",
		"lists": "Lists",
		"studentTools": "Student Tools"
	},
	topbar: {
		"openSidebar": "Open sidebar",
		"expandSidebar": "Expand sidebar",
		"collapseSidebar": "Collapse sidebar",
		"lightMode": "Light mode",
		"darkMode": "Dark mode",
		"enterFullscreen": "Enter fullscreen",
		"exitFullscreen": "Exit fullscreen",
		"logout": "Logout",
		"admin": "Admin",
		"openProfileMenu": "Open profile menu"
	},
	common: {
		"app": "App",
		"search": "Search",
		"create": "Create",
		"cancel": "Cancel",
		"edit": "Edit",
		"delete": "Delete",
		"history": "History",
		"save": "Save",
		"saveChanges": "Save Changes",
		"close": "Close",
		"loading": "Loading...",
		"id": "ID",
		"records": "Records",
		"actions": "Actions",
		"noRecords": "No records found.",
		"selectedCount": "{0} selected",
		"na": "N/A",
		"success": "Success",
		"error": "Error",
		"info": "Info",
		"required": "required"
	},
	breadcrumbs: {
		"ariaLabel": "Breadcrumb",
		"admin": "Admin",
		"dashboard": "Dashboard",
		"whatsapp": "WhatsApp",
		"users": "Users",
		"roles": "Roles",
		"plans": "Plans",
		"centers": "Centers",
		"groups": "Groups",
		"students": "Students",
		"evaluations": "Evaluations",
		"homeworks": "Assignments",
		"absenceRules": "Absence Rules",
		"messageTemplates": "Message Templates",
		"activityLogs": "Activity Logs",
		"settings": "Settings",
		"password": "Password",
		"create": "Create",
		"edit": "Edit"
	},
	profile: {
		"updatePassword": "Update Password",
		"passwordDescription": "Change your account password securely.",
		"currentPassword": "Current Password",
		"newPassword": "New Password"
	},
	users: {
		"title": "Users",
		"tableTitle": "Users Table",
		"searchUsers": "Search Users",
		"createUser": "Create User",
		"editUser": "Edit User",
		"newUser": "New User",
		"addNew": "Add a new user account to the system.",
		"editDescription": "Update user profile details or set a new password.",
		"newUserDescription": "Fill all required fields to create a user.",
		"name": "Name",
		"role": "Role",
		"confirmPassword": "Confirm Password",
		"newPassword": "New Password",
		"createdAt": "Created At",
		"deleteConfirm": "Delete \"{name}\"? This action cannot be undone.",
		"deleteUser": "Delete User"
	},
	roles: {
		"title": "Roles",
		"tableTitle": "Roles Table",
		"searchRoles": "Search Roles",
		"createRole": "Create Role",
		"editRole": "Edit Role",
		"permissions": "Permissions",
		"roleName": "Role Name",
		"createdAt": "Created At",
		"permissionsCount": "Permissions",
		"createDescription": "Define a role and attach permissions for admin access control.",
		"editDescription": "Update role name and permissions mappings.",
		"saveRole": "Save Role",
		"deleteConfirm": "Delete role \"{name}\"? This action cannot be undone.",
		"deleteRole": "Delete Role",
		"adminRoleProtected": "Admin role is protected and cannot be edited or deleted."
	},
	plans: {
		"title": "Plans",
		"tableTitle": "Plans Table",
		"searchPlans": "Search Plans",
		"createPlan": "Create Plan",
		"editPlan": "Edit Plan",
		"newPlan": "New Plan",
		"planName": "Plan Name",
		"pointsCount": "Points Count",
		"pointsActions": "Plan Points",
		"exportPoints": "Export Plan Points",
		"importPoints": "Import Plan Points",
		"importFile": "XLSX File",
		"importFileRequired": "Please choose an XLSX file.",
		"importHint": "Importing replaces this plan's points. Expected columns: plan point, points, certificate, surah name, part name, three parts.",
		"importFailed": "Could not import plan points.",
		"importSuccess": "Plan points imported successfully.",
		"createdAt": "Created At",
		"createDescription": "Add a new student plan type.",
		"editDescription": "Update the selected plan details.",
		"deleteConfirm": "Delete plan \"{name}\"? This action cannot be undone.",
		"deletePlan": "Delete Plan"
	},
	centers: {
		"title": "Centers",
		"tableTitle": "Centers Table",
		"searchCenters": "Search Centers",
		"createCenter": "Create Center",
		"editCenter": "Edit Center",
		"newCenter": "New Center",
		"centerName": "Center Name",
		"phone": "Phone",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneRequired": "Phone number is required.",
		"phoneErrorInvalid": "Invalid number.",
		"phoneErrorInvalidCountryCode": "Invalid country code.",
		"phoneErrorTooShort": "Number is too short.",
		"phoneErrorTooLong": "Number is too long.",
		"phoneErrorInvalidLength": "Invalid number length.",
		"whatsappGroup": "WhatsApp Group ID",
		"noWhatsappGroups": "No WhatsApp groups found. Connect WhatsApp first, then reload this page.",
		"workingDays": "Working Days",
		"createdAt": "Created At",
		"createDescription": "Add a center with phone and working days.",
		"editDescription": "Update center details and schedule.",
		"deleteConfirm": "Delete center \"{name}\"? This action cannot be undone.",
		"deleteCenter": "Delete Center"
	},
	groups: {
		"title": "Groups",
		"tableTitle": "Groups Table",
		"searchGroups": "Search Groups",
		"createGroup": "Create Group",
		"editGroup": "Edit Group",
		"newGroup": "New Group",
		"groupName": "Group Name",
		"center": "Center",
		"createdAt": "Created At",
		"openHomeworkReport": "Open Group Assignments Page",
		"createDescription": "Create a group and assign it to a center.",
		"editDescription": "Update group name or change its center.",
		"deleteConfirm": "Delete group \"{name}\"? This action cannot be undone.",
		"deleteGroup": "Delete Group"
	},
	students: {
		"title": "Students",
		"tableTitle": "Students Table",
		"searchStudents": "Search Students",
		"createStudent": "Create Student",
		"editStudent": "Edit Student",
		"newStudent": "New Student",
		"studentName": "Student Name",
		"firstName": "First Name",
		"secondName": "Second Name",
		"middleName": "Middle Name",
		"lastName": "Last Name",
		"idNumber": "ID Number",
		"parentPhone": "Parent Phone",
		"phone": "Phone",
		"phonePlaceholder": "+9627XXXXXXXX",
		"phoneOneRequired": "At least one phone number is required.",
		"phoneErrorInvalid": "Invalid number.",
		"phoneErrorInvalidCountryCode": "Invalid country code.",
		"phoneErrorTooShort": "Number is too short.",
		"phoneErrorTooLong": "Number is too long.",
		"phoneErrorInvalidLength": "Invalid number length.",
		"dateOfBirth": "Date of Birth",
		"group": "Group",
		"plan": "Plan",
		"admin": "Responsible",
		"status": "Status",
		"statusActive": "Active",
		"statusInactive": "Inactive",
		"statusFrozen": "Frozen",
		"freezeStudent": "Freeze Student",
		"unfreezeStudent": "Unfreeze Student",
		"freezeFrom": "From Date",
		"freezeTo": "To Date",
		"freezeReason": "Freeze Reason",
		"freezeContactPhone": "Contact Number",
		"freezeFailed": "Could not freeze this student.",
		"frozenSuccess": "Student frozen successfully.",
		"unfreezeConfirm": "Unfreeze student \"{name}\"?",
		"unfreezeFailed": "Could not unfreeze this student.",
		"unfrozenSuccess": "Student unfrozen successfully.",
		"congratulatory": "Congratulatory Message",
		"congratulatoryReason": "Message Content",
		"sendCongratulatory": "Send Congratulatory",
		"congratulatoryFailed": "Could not send congratulatory message.",
		"congratulatorySent": "Congratulatory message sent successfully.",
		"exportStudents": "Export Students",
		"importStudents": "Import Students",
		"filterByCenter": "Filter by Center",
		"exportNow": "Export",
		"importNow": "Import",
		"importFile": "XLSX File",
		"importFileRequired": "Please choose an XLSX file.",
		"importHint": "Use an XLSX file with the same headers from export.",
		"importFailed": "Could not import students.",
		"importSuccess": "Students imported successfully.",
		"createdAt": "Created At",
		"noGroupsForCenter": "No groups found for the selected center.",
		"createDescription": "Add a student and assign center, group, and plan.",
		"editDescription": "Update student profile details.",
		"deleteConfirm": "Delete student \"{name}\"? This action cannot be undone.",
		"deleteStudent": "Delete Student"
	},
	evaluations: {
		"title": "Evaluations",
		"tableTitle": "Evaluations Table",
		"searchEvaluations": "Search Evaluations",
		"createEvaluation": "Create Evaluation",
		"editEvaluation": "Edit Evaluation",
		"newEvaluation": "New Evaluation",
		"createDescription": "Select center and date, then score student evaluations.",
		"editDescription": "Update attendance and scores for this evaluation.",
		"scoreFieldMode": "Score Field",
		"center": "Center",
		"date": "Date",
		"student": "Student",
		"attendance": "Attendance",
		"present": "Present",
		"excusedAbsence": "Excused Absence",
		"absence": "Absence",
		"exempt": "Exempt",
		"alhifz": "Memorization",
		"warud": "Daily Recital",
		"akhlaqi": "Behavior",
		"tajwid": "Tajwid",
		"note": "Note",
		"loadStudents": "Load Students",
		"studentsList": "Students List",
		"studentsHint": "You can adjust attendance and scores before saving.",
		"noStudentsLoaded": "Pick a center and date, then load students.",
		"alreadyExists": "An evaluation already exists for this center and date.",
		"openExisting": "Open Existing Evaluation",
		"status": "Absence Alerts",
		"alertsPending": "Pending",
		"alertsSent": "Sent",
		"createdAt": "Created At",
		"openReport": "Open Evaluation Report",
		"sendAlerts": "Send Absence Alerts",
		"sendAlertsConfirm": "Send absence alerts for this evaluation now?",
		"sendAlertsFailed": "Could not send absence alerts.",
		"deleteConfirm": "Delete evaluation for {center} on {date}?",
		"deleteEvaluation": "Delete Evaluation",
		"deleted": "Evaluation deleted successfully.",
		"deleteFailed": "Could not delete evaluation."
	},
	homeworks: {
		"title": "Assignments",
		"tableTitle": "Assignments Table",
		"searchHomeworks": "Search Assignments",
		"createHomework": "Create Assignment",
		"editHomework": "Edit Assignment",
		"newHomework": "New Assignment",
		"createDescription": "Select center and date, then load students and mark completed points.",
		"editDescription": "Update unawarded points and save this homework.",
		"center": "Center",
		"date": "Date",
		"student": "Student",
		"studentsList": "Students List",
		"studentsHint": "Each student shows twenty next plan-point slots.",
		"noStudentsLoaded": "Pick a center and date, then load students.",
		"loadStudents": "Load Students",
		"alreadyExists": "A homework already exists for this center and date.",
		"openExisting": "Open Existing Assignment",
		"progress": "Student's latest reached point",
		"currentPosition": "Student's latest reached point",
		"notStarted": "Not started",
		"nextPoints": "Next Points",
		"noPlanPoints": "No plan points are available for this student.",
		"pointValue": "{points} points",
		"done": "Done",
		"awarded": "Awarded",
		"balance": "Balance",
		"pointsAdjustment": "Balance Adjustment",
		"pointsAdjustmentHint": "Use a positive number to add points or a negative number to deduct points.",
		"balanceAfterAdjustment": "After Adjustment",
		"manualAdjustmentsTotal": "Manual adjustments total: {points}",
		"selectedPointsTotal": "Selected points total: {points}",
		"studentsCount": "Students",
		"completedPointsCount": "Completed Points",
		"createdAt": "Created At",
		"pointsHistory": "Points History",
		"historyDate": "Date",
		"planPoint": "Plan Point",
		"points": "Points",
		"balanceAfter": "Balance After",
		"noHistory": "No point history for this student.",
		"historyFailed": "Could not load points history.",
		"deleteConfirm": "Delete homework for {center} on {date}?",
		"deleteHomework": "Delete Assignment",
		"deleted": "Assignment deleted successfully.",
		"deleteFailed": "Could not delete assignment."
	},
	absenceRules: {
		"title": "Absence Rules",
		"tableTitle": "Absence Rules Table",
		"searchRules": "Search Absence Rules",
		"createRule": "Create Absence Rule",
		"editRule": "Edit Absence Rule",
		"newRule": "New Absence Rule",
		"center": "Center",
		"allCenters": "All Centers",
		"centerOptionalHint": "Leave empty to apply this rule to all centers.",
		"attendanceType": "Attendance Type",
		"attendanceAbsence": "Absence",
		"attendanceExcusedAbsence": "Excused Absence",
		"occurrenceNumber": "Occurrence Number",
		"action": "Action",
		"actionFreezeStudent": "Freeze Student",
		"actionDismissStudent": "Dismiss Student",
		"deductionPointsCount": "Deduction Points",
		"messageTemplate": "Message Template",
		"noTemplate": "No Template",
		"freezeReason": "Freeze Reason",
		"freezeWorkingDays": "Freeze Working Days Count",
		"sendToCenterGroup": "Send also to center group",
		"isActive": "Active",
		"status": "Status",
		"active": "Active",
		"inactive": "Inactive",
		"createdAt": "Created At",
		"createDescription": "Set attendance type, occurrence, action, and deduction points.",
		"editDescription": "Update rule conditions and execution behavior.",
		"deleteConfirm": "Delete absence rule for \"{center}\" (occurrence {occurrence})?",
		"deleteRule": "Delete Rule",
		"deleted": "Absence rule deleted successfully.",
		"deleteFailed": "Could not delete absence rule."
	},
	messageTemplates: {
		"title": "Message Templates",
		"tableTitle": "Message Templates Table",
		"searchTemplates": "Search Message Templates",
		"createTemplate": "Create Message Template",
		"editTemplate": "Edit Message Template",
		"newTemplate": "New Message Template",
		"templateName": "Template Name",
		"key": "Key",
		"locale": "Locale",
		"localeArabic": "Arabic",
		"localeEnglish": "English",
		"content": "Message Content",
		"placeholdersHint": "You can use placeholders like: student.full_name, evaluation.date_ar, freeze.reason, rule.deduction_points_count",
		"isActive": "Active",
		"status": "Status",
		"active": "Active",
		"inactive": "Inactive",
		"createdAt": "Created At",
		"createDescription": "Create reusable message templates for the system.",
		"editDescription": "Update template text and placeholder usage.",
		"deleteConfirm": "Delete message template \"{name}\"?",
		"deleteTemplate": "Delete Template",
		"deleted": "Message template deleted successfully.",
		"deleteFailed": "Could not delete message template."
	},
	days: {
		"sunday": "Sunday",
		"monday": "Monday",
		"tuesday": "Tuesday",
		"wednesday": "Wednesday",
		"thursday": "Thursday",
		"friday": "Friday",
		"saturday": "Saturday"
	},
	activityLogs: {
		"title": "Activity Logs",
		"tableTitle": "Activity Logs",
		"searchLogs": "Search Logs",
		"historyFor": "History: {name}",
		"noHistory": "No activity history found for this item.",
		"noChanges": "No before/after changes captured for this event.",
		"field": "Field",
		"before": "Before",
		"after": "After",
		"by": "By",
		"description": "Description",
		"event": "Event",
		"subject": "Subject",
		"causer": "Causer",
		"createdAt": "Created At"
	},
	dashboard: {
		"title": "Dashboard",
		"eyebrow": "Live overview",
		"subtitle": "A connected view of students, attendance, assignments, centers, and WhatsApp status.",
		"empty": "No data yet.",
		"percentValue": "{value}%",
		"summaryStrip": {
			"ariaLabel": "Dashboard summary",
			"centers": "{count} centers",
			"groups": "{count} groups",
			"plans": "{count} plans",
			"whatsapp": "{connected}/{total} WhatsApp"
		},
		"metrics": {
			"students": "Students",
			"studentsSubtitle": "{active} active, {frozen} frozen",
			"attendanceRate": "Attendance rate",
			"attendanceSubtitle": "{present} present out of {total} in 30 days",
			"homeworkPoints": "Assignment points",
			"homeworkSubtitle": "{points} points awarded across {count} assignments this month",
			"evaluations": "Monthly evaluations",
			"evaluationsSubtitle": "{centers} centers and {groups} groups"
		},
		"charts": {
			"attendanceTrend": "Attendance Trend",
			"attendanceTrendSubtitle": "Last 14 days from evaluation records",
			"studentStatus": "Student Status",
			"studentStatusSubtitle": "Current student distribution by status",
			"homeworkProgress": "Assignment Completion",
			"homeworkProgressSubtitle": "Latest assignments, completed versus pending"
		},
		"statuses": {
			"active": "Active",
			"frozen": "Frozen",
			"inactive": "Inactive"
		},
		"attendance": {
			"present": "Present",
			"absent": "Absent",
			"excused": "Excused"
		},
		"homeworks": {
			"completed": "Completed",
			"pending": "Pending"
		},
		"alerts": {
			"title": "Signals",
			"subtitle": "Operational items that may need follow-up",
			"studentsWithoutPlan": {
				"title": "Students without a plan",
				"description": "{count} students need a plan assignment"
			},
			"studentsWithoutGroup": {
				"title": "Students without a group",
				"description": "{count} students need a group assignment"
			},
			"failedAbsenceMessages": {
				"title": "Failed absence messages",
				"description": "{count} messages failed in the last 30 days"
			},
			"recentEvaluations": {
				"title": "Recent evaluations",
				"description": "{count} evaluations in the last 7 days"
			},
			"whatsappDevices": {
				"title": "WhatsApp devices",
				"description": "{connected} of {total} devices connected"
			}
		},
		"centerPerformance": {
			"title": "Center Performance",
			"subtitle": "Most active centers by student count",
			"meta": "{active} active of {students} students, {groups} groups",
			"activityValue": "{evaluations} evals / {homeworks} assignments"
		},
		"recentActivity": {
			"title": "Recent Activity",
			"subtitle": "Latest evaluations, assignments, and absence alerts"
		},
		"activityTypes": {
			"evaluation": "Evaluation",
			"homework": "Assignment",
			"absence": "Absence"
		},
		"actions": {
			"title": "Quick Actions",
			"subtitle": "Shortcuts for common daily work",
			"createStudent": "Add Student",
			"createStudentMeta": "Open a new student form",
			"createEvaluation": "Add Evaluation",
			"createEvaluationMeta": "Pick center and date",
			"createHomework": "Add Assignment",
			"createHomeworkMeta": "Record student progress"
		}
	},
	whatsapp: {
		"title": "WhatsApp",
		"description": "Manage your WhatsApp session and send quick test messages.",
		"deviceFallback": "Main Device",
		"deleteDevice": "Delete Device",
		"deleteConfirm": "Delete device \"{name}\"? This will reset the current session.",
		"deviceDeleted": "Device deleted successfully.",
		"deleteFailed": "Could not delete the device.",
		"apiMissing": "WhatsApp API is not configured.",
		"apiMissingHelp": "Set WHATSAPP_API_URL (and optional WHATSAPP_API_KEY) in your environment file.",
		"instructionsTitle": "Use WhatsApp on this system",
		"step1": "Open WhatsApp on your phone.",
		"step2": "Tap Menu on Android, or Settings on iPhone.",
		"step3": "Tap Linked devices, then Link a device.",
		"step4": "Point your phone at this screen to scan the QR code.",
		"scanHint": "QR refreshes automatically every 30 seconds.",
		"refreshNow": "Refresh now",
		"connected": "Device is connected. You can send a message now.",
		"phone": "Phone",
		"message": "Message",
		"phonePlaceholder": "962799988888",
		"messagePlaceholder": "Test",
		"send": "Send",
		"sendSuccess": "Message sent successfully.",
		"sendFailed": "Could not send WhatsApp message.",
		"refreshFailed": "Could not refresh QR state."
	},
	settings: {
		"title": "Settings",
		"branding": "Branding",
		"brandingDescription": "Control app name, tagline, and branding assets used in sidebar and login.",
		"brandName": "Brand Name",
		"brandTagline": "Brand Tagline",
		"lightModeLogo": "Light Mode Logo",
		"darkModeLogo": "Dark Mode Logo",
		"appIcon": "App Icon",
		"noLogoUploaded": "No logo uploaded",
		"uploadLightLogo": "Upload Light Logo",
		"uploadDarkLogo": "Upload Dark Logo",
		"uploadIcon": "Upload Icon",
		"recommendedLogo": "Recommended: transparent logo, around 36px height.",
		"recommendedDarkLogo": "Use a light-colored logo for dark backgrounds.",
		"recommendedIcon": "Recommended: square icon at 48x48px or 64x64px.",
		"currentLightModeLogo": "Current light mode logo",
		"currentDarkModeLogo": "Current dark mode logo",
		"currentAppIcon": "Current app icon",
		"localization": "Localization",
		"localizationDescription": "Set default language and interface direction (LTR/RTL).",
		"defaultLanguage": "Default Language",
		"interfaceDirection": "Interface Direction",
		"dateTime": "Date & Time",
		"dateTimeDescription": "Set global timezone and formatting standards.",
		"dateFormat": "Date Format",
		"timeFormat": "Time Format",
		"timezone": "Timezone",
		"searchTimezone": "Search timezone...",
		"appearance": "Appearance",
		"appearanceDescription": "Customize mode, component shape, and accent color for the active theme.",
		"mode": "Mode",
		"componentShape": "Component Shape",
		"sidebarBehavior": "Sidebar Size",
		"sidebarDefault": "Default",
		"sidebarCondensed": "Condensed",
		"sidebarHidden": "Hidden",
		"sidebarSmallHoverActive": "Small Hover Active",
		"sidebarSmallHover": "Small Hover",
		"fontFamily": "Font Family",
		"accentColor": "Accent Color ({mode})",
		"light": "Light",
		"dark": "Dark",
		"compact": "Compact",
		"comfortable": "Comfortable",
		"rounded": "Rounded",
		"accent": "Accent",
		"english": "English",
		"arabic": "Arabic",
		"ltr": "LTR",
		"rtl": "RTL",
		"uploadAppIcon": "Upload App Icon",
		"uploadDarkModeLogo": "Upload Dark Mode Logo",
		"uploadLightModeLogo": "Upload Light Mode Logo"
	},
	uploads: {
		"uploadImage": "Upload Image",
		"current": "Current",
		"selected": "Selected",
		"selectedPreview": "Selected preview",
		"noImageSet": "No image set",
		"noFileSelected": "No file selected",
		"allowedFormats": "Allowed: JPG, PNG, WEBP. Max size: 2MB.",
		"upload": "Upload",
		"uploadCompleted": "Upload completed."
	},
	notifications: {
		"settingsSaved": "Your changes were saved successfully.",
		"settingsSavedTitle": "Settings Saved",
		"saveFailedTitle": "Save Failed",
		"saveFailedDetail": "Could not save settings. Please try again.",
		"loadFailedTitle": "Load Failed",
		"loadFailedDetail": "Could not load table data. Please try again.",
		"requestFailedTitle": "Request Failed",
		"requestFailedDetail": "Something went wrong. Please try again.",
		"deleteFailedTitle": "Delete Failed",
		"deleteUserFailed": "Could not delete this user.",
		"deleteRoleFailed": "Could not delete this role.",
		"deletePlanFailed": "Could not delete this plan.",
		"deleteCenterFailed": "Could not delete this center.",
		"deleteGroupFailed": "Could not delete this group.",
		"deleteStudentFailed": "Could not delete this student.",
		"userDeleted": "User deleted successfully.",
		"roleDeleted": "Role deleted successfully.",
		"planDeleted": "Plan deleted successfully.",
		"centerDeleted": "Center deleted successfully.",
		"groupDeleted": "Group deleted successfully.",
		"studentDeleted": "Student deleted successfully.",
		"imageUploaded": "Image uploaded successfully.",
		"uploadFailedTitle": "Upload Failed",
		"uploadFailedDetail": "Could not upload image. Please use JPG, PNG, or WEBP under 2MB."
	},
	errors: {
		"forbidden": {
			"title": "Access Denied",
			"description": "You do not have permission to access this page."
		},
		"notFound": {
			"title": "Page Not Found",
			"description": "The page you requested could not be found."
		},
		"expired": {
			"title": "Session Expired",
			"description": "Your session has expired. Please refresh and try again."
		},
		"serverError": {
			"title": "Server Error",
			"description": "Something went wrong on our side. Please try again in a moment."
		},
		"unavailable": {
			"title": "Service Unavailable",
			"description": "The service is temporarily unavailable. Please try again shortly."
		},
		"actions": {
			"backToDashboard": "Back to Dashboard",
			"backToHome": "Back to Home",
			"tryAgain": "Try Again"
		}
	}
};
//#endregion
//#region resources/js/i18n/index.js
var SUPPORTED_LOCALES = ["en", "ar"];
var i18nInstance = null;
var normalizeLocale = (locale) => SUPPORTED_LOCALES.includes(locale) ? locale : "ar";
var createAppI18n = (locale = "ar") => {
	i18nInstance = createI18n({
		legacy: false,
		locale: normalizeLocale(locale),
		fallbackLocale: "ar",
		messages: {
			en: en_default,
			ar: ar_default
		}
	});
	return i18nInstance;
};
var setI18nLocale = (locale) => {
	if (!i18nInstance) return;
	i18nInstance.global.locale.value = normalizeLocale(locale);
};
//#endregion
//#region resources/js/ssr.js
createServer((page) => createInertiaApp({
	page,
	render: renderToString,
	title: (title) => title ? `${title} | Vita` : "Vita",
	resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, /* #__PURE__ */ Object.assign({
		"./Pages/Admin/AbsenceRules/Create.vue": () => import("./assets/Create-D83jvXA_.js"),
		"./Pages/Admin/AbsenceRules/Edit.vue": () => import("./assets/Edit-DrHZpQIc.js"),
		"./Pages/Admin/AbsenceRules.vue": () => import("./assets/AbsenceRules-CQsFJjYy.js"),
		"./Pages/Admin/ActivityLogs.vue": () => import("./assets/ActivityLogs-j_NpOiyC.js"),
		"./Pages/Admin/Centers/Create.vue": () => import("./assets/Create-7BcM4iix.js"),
		"./Pages/Admin/Centers/Edit.vue": () => import("./assets/Edit-B-yt7fnu.js"),
		"./Pages/Admin/Centers.vue": () => import("./assets/Centers--lz-S_9_.js"),
		"./Pages/Admin/Dashboard.vue": () => import("./assets/Dashboard-kBPVpDSp.js"),
		"./Pages/Admin/Evaluations/Create.vue": () => import("./assets/Create-Gggp8wy1.js"),
		"./Pages/Admin/Evaluations/Edit.vue": () => import("./assets/Edit-CxOHLL44.js"),
		"./Pages/Admin/Evaluations.vue": () => import("./assets/Evaluations-CNmgsTbz.js"),
		"./Pages/Admin/Groups/Create.vue": () => import("./assets/Create-DfQ8Fs3O.js"),
		"./Pages/Admin/Groups/Edit.vue": () => import("./assets/Edit-CEYTjaHU.js"),
		"./Pages/Admin/Groups.vue": () => import("./assets/Groups-CIiXYAOw.js"),
		"./Pages/Admin/Homeworks/Create.vue": () => import("./assets/Create-DvoeK9ol.js"),
		"./Pages/Admin/Homeworks/Edit.vue": () => import("./assets/Edit-Cvf3SCj7.js"),
		"./Pages/Admin/Homeworks.vue": () => import("./assets/Homeworks-DDoYLJj-.js"),
		"./Pages/Admin/MessageTemplates/Create.vue": () => import("./assets/Create-BqvoCEyO.js"),
		"./Pages/Admin/MessageTemplates/Edit.vue": () => import("./assets/Edit-BSAbvDiy.js"),
		"./Pages/Admin/MessageTemplates.vue": () => import("./assets/MessageTemplates-BbP0Hhaq.js"),
		"./Pages/Admin/Plans/Create.vue": () => import("./assets/Create-_uXpCdKW.js"),
		"./Pages/Admin/Plans/Edit.vue": () => import("./assets/Edit-BLqaOTv7.js"),
		"./Pages/Admin/Plans.vue": () => import("./assets/Plans-CgQXAjvl.js"),
		"./Pages/Admin/Profile/Password.vue": () => import("./assets/Password-BWWHDiiw.js"),
		"./Pages/Admin/Roles/Create.vue": () => import("./assets/Create-Crb-VDY7.js"),
		"./Pages/Admin/Roles/Edit.vue": () => import("./assets/Edit-C6yQE1qa.js"),
		"./Pages/Admin/Roles.vue": () => import("./assets/Roles-TWaqSPv4.js"),
		"./Pages/Admin/Settings.vue": () => import("./assets/Settings-BTN6zCrM.js"),
		"./Pages/Admin/Students/Create.vue": () => import("./assets/Create-BjLfafnJ2.js"),
		"./Pages/Admin/Students/Edit.vue": () => import("./assets/Edit-BTF_6m0k2.js"),
		"./Pages/Admin/Students.vue": () => import("./assets/Students-C7xsBdvb.js"),
		"./Pages/Admin/Users/Create.vue": () => import("./assets/Create-BlmJILNh2.js"),
		"./Pages/Admin/Users/Edit.vue": () => import("./assets/Edit-BuqyisGK2.js"),
		"./Pages/Admin/Users.vue": () => import("./assets/Users-DB0dTQhb.js"),
		"./Pages/Admin/WhatsApp.vue": () => import("./assets/WhatsApp-Bxq6xALJ.js"),
		"./Pages/Auth/Login.vue": () => import("./assets/Login-CbLSJO-7.js"),
		"./Pages/Error.vue": () => import("./assets/Error-DG2VQrdd.js"),
		"./Pages/Evaluations/Report.vue": () => import("./assets/Report-Co3iBZMA.js"),
		"./Pages/Groups/HomeworkReport.vue": () => import("./assets/HomeworkReport-CMeMonD4.js")
	})),
	setup({ App, props, plugin }) {
		const i18n = createAppI18n(props.initialPage?.props?.systemSettings?.language ?? "en");
		return createSSRApp({ render: () => h(App, props) }).use(plugin).use(i18n).use(PrimeVue, { theme: {
			preset: Aura,
			options: { darkModeSelector: ".dark" }
		} });
	}
}));
//#endregion
export { setI18nLocale as t };
