<?php

return [
    'number_prefix' => 'HMT',
    'default_theme' => 'blue',
    'default_font' => 'classic',
    'default_themes' => [
        'male' => 'blue',
        'female' => 'rose',
    ],
    'themes' => [
        'blue' => [
            'label' => 'أزرق وذهبي',
            'frame' => 'certificate-frame.svg',
            'heading_color' => '#B67A20',
            'student_name_color' => '#0F537F',
            'content_color' => '#263A3D',
            'accent_color' => '#086C7C',
        ],
        'emerald' => [
            'label' => 'زمردي وذهبي',
            'frame' => 'certificate-frame-emerald-gold.svg',
            'heading_color' => '#A97818',
            'student_name_color' => '#0B5D4B',
            'content_color' => '#243D37',
            'accent_color' => '#0F7561',
        ],
        'burgundy' => [
            'label' => 'عنّابي وذهبي',
            'frame' => 'certificate-frame-burgundy-gold.svg',
            'heading_color' => '#A56F1B',
            'student_name_color' => '#7B1E3C',
            'content_color' => '#4B3039',
            'accent_color' => '#A33A59',
        ],
        'navy' => [
            'label' => 'كحلي وذهبي',
            'frame' => 'certificate-frame-navy-gold.svg',
            'heading_color' => '#A8781D',
            'student_name_color' => '#173F6B',
            'content_color' => '#27364A',
            'accent_color' => '#2B5F91',
        ],
        'purple' => [
            'label' => 'بنفسجي وذهبي',
            'frame' => 'certificate-frame-purple-gold.svg',
            'heading_color' => '#A47A19',
            'student_name_color' => '#5D2E8C',
            'content_color' => '#40334D',
            'accent_color' => '#7A4BB0',
        ],
        'black' => [
            'label' => 'أسود وذهبي',
            'frame' => 'certificate-frame-black-gold.svg',
            'heading_color' => '#9A6D16',
            'student_name_color' => '#222222',
            'content_color' => '#303030',
            'accent_color' => '#5A5A5A',
        ],
        'turquoise' => [
            'label' => 'تركواز وذهبي',
            'frame' => 'certificate-frame-turquoise-gold.svg',
            'heading_color' => '#A67818',
            'student_name_color' => '#087E8B',
            'content_color' => '#28474B',
            'accent_color' => '#087E8B',
        ],
        'rose' => [
            'label' => 'وردي غباري',
            'frame' => 'certificate-frame-rose-gold.svg',
            'heading_color' => '#A36838',
            'student_name_color' => '#A04E68',
            'content_color' => '#5D3E47',
            'accent_color' => '#A04E68',
        ],
        'bronze' => [
            'label' => 'برونزي وذهبي',
            'frame' => 'certificate-frame-bronze-gold.svg',
            'heading_color' => '#925C19',
            'student_name_color' => '#704126',
            'content_color' => '#4A382E',
            'accent_color' => '#9C633C',
        ],
        'royal' => [
            'label' => 'أزرق ملكي وذهبي',
            'frame' => 'certificate-frame-royal-gold.svg',
            'heading_color' => '#A87818',
            'student_name_color' => '#1F3C88',
            'content_color' => '#263556',
            'accent_color' => '#3057B9',
        ],
        'indigo' => [
            'label' => 'نيلي وذهبي',
            'frame' => 'certificate-frame-indigo-gold.svg',
            'heading_color' => '#9E7620',
            'student_name_color' => '#3F2C70',
            'content_color' => '#393247',
            'accent_color' => '#6C5AB5',
        ],
        'crimson' => [
            'label' => 'قرمزي وذهبي',
            'frame' => 'certificate-frame-crimson-gold.svg',
            'heading_color' => '#A2741C',
            'student_name_color' => '#8B1831',
            'content_color' => '#4A2A31',
            'accent_color' => '#BF3D5A',
        ],
        'coral' => [
            'label' => 'مرجاني وذهبي',
            'frame' => 'certificate-frame-coral-gold.svg',
            'heading_color' => '#A26726',
            'student_name_color' => '#B84940',
            'content_color' => '#523532',
            'accent_color' => '#B84940',
        ],
        'orange' => [
            'label' => 'برتقالي وذهبي',
            'frame' => 'certificate-frame-orange-gold.svg',
            'heading_color' => '#A8560F',
            'student_name_color' => '#A74F0D',
            'content_color' => '#4B3423',
            'accent_color' => '#A74F0D',
        ],
        'copper' => [
            'label' => 'نحاسي',
            'frame' => 'certificate-frame-copper-gold.svg',
            'heading_color' => '#985619',
            'student_name_color' => '#8C4021',
            'content_color' => '#49352B',
            'accent_color' => '#8C4021',
        ],
        'olive' => [
            'label' => 'زيتوني وذهبي',
            'frame' => 'certificate-frame-olive-gold.svg',
            'heading_color' => '#7E711B',
            'student_name_color' => '#60662F',
            'content_color' => '#414330',
            'accent_color' => '#60662F',
        ],
        'forest' => [
            'label' => 'أخضر غابة وذهبي',
            'frame' => 'certificate-frame-forest-gold.svg',
            'heading_color' => '#936918',
            'student_name_color' => '#1E5A3F',
            'content_color' => '#2E4038',
            'accent_color' => '#3C8362',
        ],
        'slate' => [
            'label' => 'رمادي أردوازي',
            'frame' => 'certificate-frame-slate-gold.svg',
            'heading_color' => '#8D691C',
            'student_name_color' => '#3F5465',
            'content_color' => '#303C45',
            'accent_color' => '#3F5465',
        ],
        'lavender' => [
            'label' => 'لافندر وذهبي',
            'frame' => 'certificate-frame-lavender-gold.svg',
            'heading_color' => '#956D23',
            'student_name_color' => '#7A5A8C',
            'content_color' => '#493E50',
            'accent_color' => '#7A5A8C',
        ],
        'mint' => [
            'label' => 'نعناعي وذهبي',
            'frame' => 'certificate-frame-mint-gold.svg',
            'heading_color' => '#96701D',
            'student_name_color' => '#347565',
            'content_color' => '#304740',
            'accent_color' => '#3D7A6C',
        ],
    ],
    'font_families' => [
        'amiri' => [
            'family' => 'Certificate Amiri',
            'regular_css_path' => '../fonts/certificate/Amiri-Regular.ttf',
            'bold_css_path' => '../fonts/certificate/Amiri-Bold.ttf',
            'regular_path' => 'fonts/certificate/Amiri-Regular.ttf',
            'bold_path' => 'fonts/certificate/Amiri-Bold.ttf',
        ],
        'naskh' => [
            'family' => 'Certificate Naskh',
            'regular_css_path' => '../fonts/certificate/NotoNaskhArabic-Regular.ttf',
            'bold_css_path' => '../fonts/certificate/NotoNaskhArabic-Bold.ttf',
            'regular_path' => 'fonts/certificate/NotoNaskhArabic-Regular.ttf',
            'bold_path' => 'fonts/certificate/NotoNaskhArabic-Bold.ttf',
        ],
        'kufi' => [
            'family' => 'Certificate Kufi',
            'regular_css_path' => '../fonts/certificate/NotoKufiArabic-Regular.ttf',
            'bold_css_path' => '../fonts/certificate/NotoKufiArabic-Bold.ttf',
            'regular_path' => 'fonts/certificate/NotoKufiArabic-Regular.ttf',
            'bold_path' => 'fonts/certificate/NotoKufiArabic-Bold.ttf',
        ],
        'sans_arabic' => [
            'family' => 'Certificate Sans Arabic',
            'regular_css_path' => '../fonts/certificate/NotoSansArabic-Regular.ttf',
            'bold_css_path' => '../fonts/certificate/NotoSansArabic-Bold.ttf',
            'regular_path' => 'fonts/certificate/NotoSansArabic-Regular.ttf',
            'bold_path' => 'fonts/certificate/NotoSansArabic-Bold.ttf',
        ],
        'nastaliq' => [
            'family' => 'Certificate Nastaliq',
            'regular_css_path' => '../fonts/certificate/NotoNastaliqUrdu-Regular.ttf',
            'bold_css_path' => '../fonts/certificate/NotoNastaliqUrdu-Bold.ttf',
            'regular_path' => 'fonts/certificate/NotoNastaliqUrdu-Regular.ttf',
            'bold_path' => 'fonts/certificate/NotoNastaliqUrdu-Bold.ttf',
        ],
    ],
    'fonts' => [
        'classic' => [
            'label' => 'كلاسيكي (نسخ وأميري)',
            'body_family' => 'Certificate Naskh',
            'display_family' => 'Certificate Amiri',
            'families' => ['naskh', 'amiri'],
        ],
        'amiri' => [
            'label' => 'أميري بالكامل',
            'body_family' => 'Certificate Amiri',
            'display_family' => 'Certificate Amiri',
            'families' => ['amiri'],
        ],
        'naskh' => [
            'label' => 'نسخ عربي بالكامل',
            'body_family' => 'Certificate Naskh',
            'display_family' => 'Certificate Naskh',
            'families' => ['naskh'],
        ],
        'kufi' => [
            'label' => 'كوفي عربي بالكامل',
            'body_family' => 'Certificate Kufi',
            'display_family' => 'Certificate Kufi',
            'families' => ['kufi'],
        ],
        'sans_arabic' => [
            'label' => 'عربي عصري بالكامل',
            'body_family' => 'Certificate Sans Arabic',
            'display_family' => 'Certificate Sans Arabic',
            'families' => ['sans_arabic'],
        ],
        'naskh_kufi' => [
            'label' => 'كوفي احتفالي (نسخ وكوفي)',
            'body_family' => 'Certificate Naskh',
            'display_family' => 'Certificate Kufi',
            'families' => ['naskh', 'kufi'],
        ],
        'naskh_nastaliq' => [
            'label' => 'نستعليق احتفالي (نسخ ونستعليق)',
            'body_family' => 'Certificate Naskh',
            'display_family' => 'Certificate Nastaliq',
            'families' => ['naskh', 'nastaliq'],
        ],
        'sans_amiri' => [
            'label' => 'أميري عصري (حديث وأميري)',
            'body_family' => 'Certificate Sans Arabic',
            'display_family' => 'Certificate Amiri',
            'families' => ['sans_arabic', 'amiri'],
        ],
        'sans_kufi' => [
            'label' => 'كوفي عصري (حديث وكوفي)',
            'body_family' => 'Certificate Sans Arabic',
            'display_family' => 'Certificate Kufi',
            'families' => ['sans_arabic', 'kufi'],
        ],
        'sans_naskh' => [
            'label' => 'نسخ عصري (حديث ونسخ)',
            'body_family' => 'Certificate Sans Arabic',
            'display_family' => 'Certificate Naskh',
            'families' => ['sans_arabic', 'naskh'],
        ],
        'kufi_amiri' => [
            'label' => 'أميري هندسي (كوفي وأميري)',
            'body_family' => 'Certificate Kufi',
            'display_family' => 'Certificate Amiri',
            'families' => ['kufi', 'amiri'],
        ],
        'sans_nastaliq' => [
            'label' => 'نستعليق عصري (حديث ونستعليق)',
            'body_family' => 'Certificate Sans Arabic',
            'display_family' => 'Certificate Nastaliq',
            'families' => ['sans_arabic', 'nastaliq'],
        ],
    ],
    'wording' => [
        'male' => [
            'project_name' => 'الحَافِظِ المُتَمَيِّزِ',
            'intro_before_project' => 'تَتَقَدَّمُ إِدَارَةُ مَشْرُوعِ',
            'intro_after_center' => 'بِالتَّهْنِئَةِ الحَارَّةِ لِطَالِبِ العِلْمِ المُتَمَيِّزِ:',
            'achievement_intro' => 'وَذَلِكَ لِإِنْجَازِهِ',
            'achievement_suffix' => 'بِإِتْقَانٍ عَالٍ بِفَضْلِ اللهِ تَعَالَى',
            'closing_text' => 'نَسْأَلُ اللهَ لَهُ التَّوْفِيقَ وَالثَّبَاتَ، وَأَنْ يَمُنَّ عَلَيْهِ بِإِتْمَامِ حِفْظِ كِتَابِهِ الكَرِيمِ وَالعَمَلِ بِهِ.',
        ],
        'female' => [
            'project_name' => 'الحَافِظِ المُتَمَيِّزِ',
            'intro_before_project' => 'تَتَقَدَّمُ إِدَارَةُ مَشْرُوعِ',
            'intro_after_center' => 'بِالتَّهْنِئَةِ الحَارَّةِ لِطَالِبَةِ العِلْمِ المُتَمَيِّزَةِ:',
            'achievement_intro' => 'وَذَلِكَ لِإِنْجَازِهَا',
            'achievement_suffix' => 'بِإِتْقَانٍ عَالٍ بِفَضْلِ اللهِ تَعَالَى',
            'closing_text' => 'نَسْأَلُ اللهَ لَهَا التَّوْفِيقَ وَالثَّبَاتَ، وَأَنْ يَمُنَّ عَلَيْهَا بِإِتْمَامِ حِفْظِ كِتَابِهِ الكَرِيمِ وَالعَمَلِ بِهِ.',
        ],
    ],
    'title' => 'شَهادَةُ تَمَيُّزٍ وَتَقْدِيرٍ',
    'quote_first' => 'لَوْلَا المَشَقَّةُ سَادَ النَّاسُ كُلُّهُمُ',
    'quote_second' => 'الجُودُ يُفْقِرُ وَالإِقْدَامُ قَتَّالُ',
    'project_name' => 'الحَافِظِ المُتَمَيِّزِ',
    'intro_before_project' => 'تَتَقَدَّمُ إِدَارَةُ مَشْرُوعِ',
    'intro_after_center' => 'بِالتَّهْنِئَةِ الحَارَّةِ لِطَالِبِ العِلْمِ المُتَمَيِّزِ:',
    'achievement_intro' => 'وَذَلِكَ لِإِنْجَازِهِ',
    'achievement_labels' => [
        'surah' => 'سُورَةَ',
        'part' => 'جُزْءَ',
        'three_parts' => 'ثَلَاثَةَ أَجْزَاءٍ',
    ],
    'achievement_suffix' => 'بِإِتْقَانٍ عَالٍ بِفَضْلِ اللهِ تَعَالَى',
    'closing_text' => 'نَسْأَلُ اللهَ لَهُ التَّوْفِيقَ وَالثَّبَاتَ، وَأَنْ يَمُنَّ عَلَيْهِ بِإِتْمَامِ حِفْظِ كِتَابِهِ الكَرِيمِ وَالعَمَلِ بِهِ.',
    'center_manager_title' => 'تَوْقِيعُ مُدِيرِ المَرْكَزِ',
    'project_manager_title' => 'تَوْقِيعُ مُدِيرِ المَشْرُوعِ',
    'date_title' => 'تَارِيخُ الإِنْجَازِ',
    'labels' => [
        'tools' => 'أدوات الشهادة',
        'back' => 'العودة إلى شهادات الطالب',
        'download_pdf' => 'تنزيل PDF',
        'print' => 'طباعة الشهادة',
        'poem' => 'بيت الشعر',
        'left_logo' => 'شعار المركز',
        'right_logo' => 'شعار المشروع',
        'center_stamp' => 'ختم مدير المركز',
        'center_signature' => 'توقيع مدير المركز',
        'project_stamp' => 'ختم مدير المشروع',
        'project_signature' => 'توقيع مدير المشروع',
        'achievement_date' => 'تاريخ الإنجاز',
        'hijri' => 'هِجْرِيّ',
        'gregorian' => 'مِيلَادِيّ',
        'certificate_number' => 'رقم الشهادة',
    ],
    'assets' => [
        'stylesheet' => 'css/certificate.css',
        'frame' => 'images/certificate/certificate-frame.svg',
        'left_logo' => 'images/certificate/left-logo.png',
        'right_logo' => 'images/certificate/right-logo.png',
        'center_stamp' => 'images/certificate/center-stamp.png',
        'center_signature' => 'images/certificate/center-signature.png',
        'project_stamp' => 'images/certificate/project-stamp.png',
        'project_signature' => 'images/certificate/project-signature.png',
        'fonts' => [
            '../fonts/certificate/Amiri-Regular.ttf' => 'fonts/certificate/Amiri-Regular.ttf',
            '../fonts/certificate/Amiri-Bold.ttf' => 'fonts/certificate/Amiri-Bold.ttf',
            '../fonts/certificate/NotoNaskhArabic-Regular.ttf' => 'fonts/certificate/NotoNaskhArabic-Regular.ttf',
            '../fonts/certificate/NotoNaskhArabic-Bold.ttf' => 'fonts/certificate/NotoNaskhArabic-Bold.ttf',
        ],
    ],
];
